### ISSUE TITLE
Having clang installed on Windows makes choosenim skip mingw download, resulting in a crash later on

### ISSUE THREAD

**Issue by ghost** [dom96/choosenim#104]
\> choosenim 0.19.2
Downloading Nim 0.19.2 from nim-lang.org
      Info: C:\Users\user\.choosenim\downloads\nim-0.19.2.tar.gz already downloaded
 Extracting nim-0.19.2.tar.gz
   Building Nim 0.19.2
 Exception: choosenim.nim(206)       choosenim
        ... choosenim.nim(187)       performAction
        ... choosenim.nim(89)        choose
        ... choosenim.nim(72)        chooseVersion
        ... choosenim.nim(46)        installVersion
        ... builder.nim(91)          build
        ... builder.nim(23)          buildCompiler
        ... builder.nim(10)          buildFromCSources
        ... utils.nim(19)            doCmdRaw
        ... Execution failed with exit code 255
        ... Command: build.bat
        ... Output: Detecting gcc arch
        ... 'gcc' n'est pas reconnu en tant que commande interne
        ... ou externe, un programme exécutable ou un fichier de commandes.
     Error: choosenim.nim(206)       choosenim
        ... choosenim.nim(187)       performAction
        ... choosenim.nim(89)        choose
        ... choosenim.nim(72)        chooseVersion
        ... choosenim.nim(46)        installVersion
        ... builder.nim(100)         build
        ... Build failed

I confirm that after uninstalling clang (or probably also when removing it from PATH) the issue disappears.

**Comment by dom96** [comment]
Looks like this has been fixed.
