### ISSUE TITLE
choosenim stable is stuck at original install version

### ISSUE THREAD

**Issue by genotrance** [dom96/choosenim#108]
Stable is stuck at the version originally saved when choosenim first ran. My Linux box is stuck at 0.17.2 and Windows is at 0.19.0 cause that is what is in ~/.choosenim/channels/stable.

Stable should mean latest stable.

**Comment by dom96** [comment]
Choosenim requires you to explicitly ask for an update. Do you seriously want it to go to the network and possibly spend hours recompiling when you just want to switch to ``stable`` quickly via ``choosenim stable``?

Perhaps I misunderstand what you mean, if so, feel free to let me know and I'll reopen.

**Comment by genotrance** [comment]
I don't expect it to download when I say `choosenim stable` but at the very least, it should check that there's an update and tell me there's one. It's no longer stable if we have since published newer versions and have no intentions of maintaining 0.17.2 anymore.

**Comment by dom96** [comment]
I'd rather not hit the network, but we can add a hint for any use of ``choosenim <channel>`` (channel being ``stable`` or ``devel``)

**Comment by genotrance** [comment]
I think this should be closed in retrospect.
