### ISSUE TITLE
Can I choose what directory to install everything in?

### ISSUE THREAD

**Issue by arnavb** [dom96/choosenim#110]
Is there a way to choose the install directory for `choosenim`, similar to how [rustup](https://github.com/rust-lang/rustup.rs#choosing-where-to-install) uses the `RUSTUP_HOME` and `CARGO_HOME` variables to specify an installation directory?

I couldn't find any documentation for this.

**Comment by dom96** [comment]
The only way currently is with the ``--choosenimDir:<dir>`` parameter
