### ISSUE TITLE
`choosenim update self` throws HttpRequest Error

### ISSUE THREAD

**Issue by euantorano** [dom96/choosenim#116]
```
PS C:\Users\euant> choosenim update self
   Updating choosenim
[#                                                 ] 0mb 3kb/s
choosenim.nim(206)       choosenim
choosenim.nim(183)       performAction
choosenim.nim(132)       update
choosenim.nim(107)       updateSelf
download.nim(192)        downloadFile
download.nim(177)        downloadFileNim
httpclient.nim(1306)     downloadFile
Error: unhandled exception: 404 Not Found [HttpRequestError]
```

OS: Windows 10 Enterprise x64

Version: `choosenim v0.3.2 (2018-02-27 20:19:49) [windows/i386]`

Since `choosenim update self` is the recommended way to update choosenim, it would be nice to catch and handle these types of exceptions to provide a little more information (e.g. which URL caused the 404).

**Comment by dom96** [comment]
This is a bug in choosenim (exceptions should always be handled)

Run ``choosenim update self --debug`` to get info about the URL. I think I know how to fix this though.

**Comment by dom96** [comment]
Bah. Looks like choosenim won't add the .exe to the URL: https://github.com/dom96/choosenim/blob/v0.4.0/src/choosenim.nim#L82. And GitHub won't let me save an .exe binary without the .exe extension :(

**Comment by genotrance** [comment]
Is all that's needed is an `addFileExt(ExeEct)`?

**Comment by dom96** [comment]
Possibly. But AFAIK we'll get "File is in use" errors when copying over choosenim.exe anyway because of how Windows works.

**Comment by genotrance** [comment]
Does this mean we don't have choosenim self update working on Windows to date?

**Comment by dom96** [comment]
Yes, I doubt it works.
