### ISSUE TITLE
Missing nimpretty.exe

### ISSUE THREAD

**Issue by Kvothe87** [dom96/choosenim#119]
choosenim v 0.4.0 on windows

I tried to run the nimpretty but i get an error that the nimpretty.exe file is missing in the path. Checking the suggested path the file is not there.
I see other files like nimble or nimgrab

**Comment by dom96** [comment]
Pretty sure this is a Nim issue, is nimpretty.exe included in the tarballs?

**Comment by Araq** [comment]
I'm sure this is fixed now.
