### ISSUE TITLE
Change the way update works

### ISSUE THREAD

**Issue by andreaferretti** [dom96/choosenim#12]
Right now, `choosenim update` just redownloads everything and rebuilds from scratch using csources.

I think it should work this way:

* `choosenim update 0.16.0` (or in fact any tag) should be a noop - there is no need to update a fixed version
* `choosenim update "#head"` should do a git pull and then use koch to rebuild using the existing nim.

In fact, with this behaviour, the version is redundant: the only case in which it makes sense to update is when being on devel, so there could just be `choosenim update` to update #head.

With the current behaviour, choosenim is inconvenient to keep up to date with latest Nim daily - a full clone and rebuild is too slow.

**Comment by dom96** [comment]
I foresee the following two cases:

* ``choosenim update stable`` - this is a noop already when there is no new stable version.
* ``choosenim update devel`` - this defaults to a git branch so is always updated.

We can surely make the latter more efficient, but in the long run I would like to offer binary builds to avoid the unnecessary bootstrapping altogether. I think pursuing that is more worthwhile.

**Comment by andreaferretti** [comment]
Are you actually using choosenim yourself? I guess you probably stay on devel like me, so you probably want to frequently run `choosenim update devel` (I assumed one had to use #head, because devel is not mentioned in the README).

I update Nim every morning (and I guess many other users do, at this point of development), so it is convenient to do that in a reasonably short time. It is a minor annoyance, but I guess it it worth to actually update instead of reinstalling from scratch every time.

I am not sure about the binary builds, but I guess they would not be up to date with devel anyway

**Comment by dom96** [comment]
I have the Nim repo, since I often work on it, cloned into ``~/projects/nim``. Choosenim supports this by allowing me to choose a path: ``choosenim ~/projects/nim``.

Then I can update easily by cd'ing into ``~/projects/nim``. I understand that this isn't ideal for most though.

**Comment by genotrance** [comment]
One other challenge with using `git pull` is requiring git for choosenim to do the update. Most developers might have git already but still have to handle the case.

The option would be to support update only if git is available. If not, complain to the user and exit. The actual devel install can continue to use the existing method since the extracted ZIP can be converted into a git repo on the fly. 

If user asks for update: 
- Check for git
- git init if not already
- git remote add origin https://github.com/nim-lang/nim
- git pull
- Rebuild
