### ISSUE TITLE
Install failure when using user's nim configuration file.

### ISSUE THREAD

**Issue by samdmarshall** [dom96/choosenim#120]
I've been trying to install version `0.20.0` of Nim and have run into a problem with locally building the compiler and tools via `choosenim`. It seems that my `config.nims` file, which would normally be used during user compilations is being sourced for building the new language version and related tools. In my case I have the following [configuration file](https://github.com/samdmarshall/dotfiles/blob/linux/nim/config.nims) which caused building `0.20.0` to fail with: `Error: unknown warning: ShadowIdent`. I don't think that the user's configuration file should be sourced for this action.

<details>n.
<summary>Full Build Log</summary>
<pre><code>$ choosenim update stable --verbose --debug
      Info: Not sending analytics because CHOOSENIM_NO_ANALYTICS is set.
      Info: Not sending analytics because CHOOSENIM_NO_ANALYTICS is set.
   Updating stable
Downloading Nim 0.20.0 from nim-lang.org
[##################################################] 100.0% 0kb/s
      Info: Not sending analytics because CHOOSENIM_NO_ANALYTICS is set.
 Extracting nim-0.20.0.tar.xz
  Executing unxz "/home/demi/.choosenim/downloads/nim-0.20.0.tar.xz"
   Finished with exit code 0
      Info: Not sending analytics because CHOOSENIM_NO_ANALYTICS is set.
   Building Nim 0.20.0
  Executing sh build.sh
   Finished with exit code 0
     Output # OS: linux
        ... # CPU: amd64
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_assertions.nim.c -o c_code/1_2/stdlib_assertions.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_dollars.nim.c -o c_code/1_2/stdlib_dollars.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_io.nim.c -o c_code/2_2/stdlib_io.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_system.nim.c -o c_code/2_2/stdlib_system.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_parseutils.nim.c -o c_code/2_2/stdlib_parseutils.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_math.nim.c -o c_code/2_2/stdlib_math.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_algorithm.nim.c -o c_code/1_2/stdlib_algorithm.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_unicode.nim.c -o c_code/2_2/stdlib_unicode.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_strutils.nim.c -o c_code/2_2/stdlib_strutils.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_pathnorm.nim.c -o c_code/2_2/stdlib_pathnorm.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_posix.nim.c -o c_code/2_2/stdlib_posix.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_times.nim.c -o c_code/2_2/stdlib_times.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_os.nim.c -o c_code/2_2/stdlib_os.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_hashes.nim.c -o c_code/1_2/stdlib_hashes.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_strtabs.nim.c -o c_code/1_2/stdlib_strtabs.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_streams.nim.c -o c_code/2_2/stdlib_streams.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_cpuinfo.nim.c -o c_code/2_2/stdlib_cpuinfo.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_osproc.nim.c -o c_code/2_2/stdlib_osproc.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_sets.nim.c -o c_code/1_2/stdlib_sets.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/pathutils.nim.c -o c_code/2_2/pathutils.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/ropes.nim.c -o c_code/1_2/ropes.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_tables.nim.c -o c_code/1_2/stdlib_tables.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/lineinfos.nim.c -o c_code/1_2/lineinfos.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/platform.nim.c -o c_code/2_2/platform.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/prefixmatches.nim.c -o c_code/1_2/prefixmatches.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_strformat.nim.c -o c_code/2_2/stdlib_strformat.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_terminal.nim.c -o c_code/2_2/stdlib_terminal.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/options.nim.c -o c_code/2_2/options.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/msgs.nim.c -o c_code/2_2/msgs.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/wordrecg.nim.c -o c_code/1_2/wordrecg.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/idents.nim.c -o c_code/1_2/idents.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/condsyms.nim.c -o c_code/1_2/condsyms.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_sha1.nim.c -o c_code/1_2/stdlib_sha1.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_lexbase.nim.c -o c_code/2_2/stdlib_lexbase.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_parsejson.nim.c -o c_code/1_2/stdlib_parsejson.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_json.nim.c -o c_code/2_2/stdlib_json.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/extccomp.nim.c -o c_code/2_2/extccomp.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/nimblecmd.nim.c -o c_code/2_2/nimblecmd.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_parseopt.nim.c -o c_code/2_2/stdlib_parseopt.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/commands.nim.c -o c_code/2_2/commands.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/llstream.nim.c -o c_code/1_2/llstream.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/nimlexbase.nim.c -o c_code/1_2/nimlexbase.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/lexer.nim.c -o c_code/2_2/lexer.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/nimconf.nim.c -o c_code/2_2/nimconf.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_intsets.nim.c -o c_code/1_2/stdlib_intsets.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/idgen.nim.c -o c_code/1_2/idgen.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/ast.nim.c -o c_code/1_2/ast.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/rodutils.nim.c -o c_code/1_2/rodutils.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/astalgo.nim.c -o c_code/2_2/astalgo.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/parser.nim.c -o c_code/1_2/parser.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/renderer.nim.c -o c_code/1_2/renderer.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/filters.nim.c -o c_code/1_2/filters.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/filter__tmpl.nim.c -o c_code/1_2/filter__tmpl.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/syntaxes.nim.c -o c_code/1_2/syntaxes.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/trees.nim.c -o c_code/1_2/trees.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/types.nim.c -o c_code/2_2/types.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/treetab.nim.c -o c_code/1_2/treetab.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/incremental.nim.c -o c_code/1_2/incremental.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/btrees.nim.c -o c_code/1_2/btrees.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_md5.nim.c -o c_code/1_2/stdlib_md5.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/modulegraphs.nim.c -o c_code/1_2/modulegraphs.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/magicsys.nim.c -o c_code/1_2/magicsys.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/bitsets.nim.c -o c_code/1_2/bitsets.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/nimsets.nim.c -o c_code/1_2/nimsets.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/semfold.nim.c -o c_code/2_2/semfold.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/modulepaths.nim.c -o c_code/2_2/modulepaths.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/reorder.nim.c -o c_code/1_2/reorder.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/passes.nim.c -o c_code/1_2/passes.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/vmdef.nim.c -o c_code/1_2/vmdef.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/semdata.nim.c -o c_code/1_2/semdata.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/linter.nim.c -o c_code/1_2/linter.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/nimfix7prettybase.nim.c -o c_code/1_2/nimfix7prettybase.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/lookups.nim.c -o c_code/1_2/lookups.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/semtypinst.nim.c -o c_code/1_2/semtypinst.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/parampatterns.nim.c -o c_code/1_2/parampatterns.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/lowerings.nim.c -o c_code/1_2/lowerings.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/_7lib7packages7docutils7rstast.nim.c -o c_code/1_2/_7lib7packages7docutils7rstast.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/_7lib7packages7docutils7rst.nim.c -o c_code/1_2/_7lib7packages7docutils7rst.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/_7lib7packages7docutils7highlite.nim.c -o c_code/1_2/_7lib7packages7docutils7highlite.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/_7lib7packages7docutils7rstgen.nim.c -o c_code/2_2/_7lib7packages7docutils7rstgen.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_xmltree.nim.c -o c_code/1_2/stdlib_xmltree.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_uri.nim.c -o c_code/1_2/stdlib_uri.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_cgi.nim.c -o c_code/1_2/stdlib_cgi.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/typesrenderer.nim.c -o c_code/1_2/typesrenderer.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/docgen.nim.c -o c_code/2_2/docgen.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/sigmatch.nim.c -o c_code/2_2/sigmatch.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/importer.nim.c -o c_code/1_2/importer.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/procfind.nim.c -o c_code/1_2/procfind.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/pragmas.nim.c -o c_code/2_2/pragmas.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/saturate.nim.c -o c_code/1_2/saturate.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/guards.nim.c -o c_code/1_2/guards.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/sighashes.nim.c -o c_code/1_2/sighashes.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/sempass2.nim.c -o c_code/1_2/sempass2.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/cgmeth.nim.c -o c_code/1_2/cgmeth.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/aliases.nim.c -o c_code/1_2/aliases.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/patterns.nim.c -o c_code/1_2/patterns.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/dfa.nim.c -o c_code/1_2/dfa.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/injectdestructors.nim.c -o c_code/1_2/injectdestructors.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/liftlocals.nim.c -o c_code/1_2/liftlocals.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/lambdalifting.nim.c -o c_code/1_2/lambdalifting.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/closureiters.nim.c -o c_code/1_2/closureiters.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/transf.nim.c -o c_code/1_2/transf.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/vmgen.nim.c -o c_code/1_2/vmgen.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/vmdeps.nim.c -o c_code/2_2/vmdeps.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/vmmarshal.nim.c -o c_code/1_2/vmmarshal.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/gorgeimpl.nim.c -o c_code/2_2/gorgeimpl.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/macrocacheimpl.nim.c -o c_code/1_2/macrocacheimpl.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/evaltempl.nim.c -o c_code/1_2/evaltempl.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/vm.nim.c -o c_code/2_2/vm.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/semmacrosanity.nim.c -o c_code/1_2/semmacrosanity.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/pluginsupport.nim.c -o c_code/1_2/pluginsupport.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/plugins7locals.nim.c -o c_code/1_2/plugins7locals.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/plugins7itersgen.nim.c -o c_code/1_2/plugins7itersgen.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/plugins7active.nim.c -o c_code/1_2/plugins7active.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/semparallel.nim.c -o c_code/1_2/semparallel.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/sem.nim.c -o c_code/2_2/sem.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/ccgutils.nim.c -o c_code/1_2/ccgutils.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/ndi.nim.c -o c_code/1_2/ndi.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/cgendata.nim.c -o c_code/1_2/cgendata.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/ccgmerge.nim.c -o c_code/1_2/ccgmerge.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/enumtostr.nim.c -o c_code/1_2/enumtostr.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_dynlib.nim.c -o c_code/2_2/stdlib_dynlib.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/cgen.nim.c -o c_code/1_2/cgen.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/passaux.nim.c -o c_code/1_2/passaux.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/depends.nim.c -o c_code/1_2/depends.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/modules.nim.c -o c_code/1_2/modules.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/jsgen.nim.c -o c_code/1_2/jsgen.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/docgen2.nim.c -o c_code/2_2/docgen2.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/main.nim.c -o c_code/1_2/main.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/scriptconfig.nim.c -o c_code/2_2/scriptconfig.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/cmdlinehelper.nim.c -o c_code/2_2/cmdlinehelper.nim.o
        ... gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/nim.nim.c -o c_code/2_2/nim.nim.o
        ... gcc -o bin/nim c_code/1_2/stdlib_assertions.nim.o c_code/1_2/stdlib_dollars.nim.o c_code/2_2/stdlib_io.nim.o c_code/2_2/stdlib_system.nim.o c_code/2_2/stdlib_parseutils.nim.o c_code/2_2/stdlib_math.nim.o c_code/1_2/stdlib_algorithm.nim.o c_code/2_2/stdlib_unicode.nim.o c_code/2_2/stdlib_strutils.nim.o c_code/2_2/stdlib_pathnorm.nim.o c_code/2_2/stdlib_posix.nim.o c_code/2_2/stdlib_times.nim.o c_code/2_2/stdlib_os.nim.o c_code/1_2/stdlib_hashes.nim.o c_code/1_2/stdlib_strtabs.nim.o c_code/2_2/stdlib_streams.nim.o c_code/2_2/stdlib_cpuinfo.nim.o c_code/2_2/stdlib_osproc.nim.o c_code/1_2/stdlib_sets.nim.o c_code/2_2/pathutils.nim.o c_code/1_2/ropes.nim.o c_code/1_2/stdlib_tables.nim.o c_code/1_2/lineinfos.nim.o c_code/2_2/platform.nim.o c_code/1_2/prefixmatches.nim.o c_code/2_2/stdlib_strformat.nim.o c_code/2_2/stdlib_terminal.nim.o c_code/2_2/options.nim.o c_code/2_2/msgs.nim.o c_code/1_2/wordrecg.nim.o c_code/1_2/idents.nim.o c_code/1_2/condsyms.nim.o c_code/1_2/stdlib_sha1.nim.o c_code/2_2/stdlib_lexbase.nim.o c_code/1_2/stdlib_parsejson.nim.o c_code/2_2/stdlib_json.nim.o c_code/2_2/extccomp.nim.o c_code/2_2/nimblecmd.nim.o c_code/2_2/stdlib_parseopt.nim.o c_code/2_2/commands.nim.o c_code/1_2/llstream.nim.o c_code/1_2/nimlexbase.nim.o c_code/2_2/lexer.nim.o c_code/2_2/nimconf.nim.o c_code/1_2/stdlib_intsets.nim.o c_code/1_2/idgen.nim.o c_code/1_2/ast.nim.o c_code/1_2/rodutils.nim.o c_code/2_2/astalgo.nim.o c_code/1_2/parser.nim.o c_code/1_2/renderer.nim.o c_code/1_2/filters.nim.o c_code/1_2/filter__tmpl.nim.o c_code/1_2/syntaxes.nim.o c_code/1_2/trees.nim.o c_code/2_2/types.nim.o c_code/1_2/treetab.nim.o c_code/1_2/incremental.nim.o c_code/1_2/btrees.nim.o c_code/1_2/stdlib_md5.nim.o c_code/1_2/modulegraphs.nim.o c_code/1_2/magicsys.nim.o c_code/1_2/bitsets.nim.o c_code/1_2/nimsets.nim.o c_code/2_2/semfold.nim.o c_code/2_2/modulepaths.nim.o c_code/1_2/reorder.nim.o c_code/1_2/passes.nim.o c_code/1_2/vmdef.nim.o c_code/1_2/semdata.nim.o c_code/1_2/linter.nim.o c_code/1_2/nimfix7prettybase.nim.o c_code/1_2/lookups.nim.o c_code/1_2/semtypinst.nim.o c_code/1_2/parampatterns.nim.o c_code/1_2/lowerings.nim.o c_code/1_2/_7lib7packages7docutils7rstast.nim.o c_code/1_2/_7lib7packages7docutils7rst.nim.o c_code/1_2/_7lib7packages7docutils7highlite.nim.o c_code/2_2/_7lib7packages7docutils7rstgen.nim.o c_code/1_2/stdlib_xmltree.nim.o c_code/1_2/stdlib_uri.nim.o c_code/1_2/stdlib_cgi.nim.o c_code/1_2/typesrenderer.nim.o c_code/2_2/docgen.nim.o c_code/2_2/sigmatch.nim.o c_code/1_2/importer.nim.o c_code/1_2/procfind.nim.o c_code/2_2/pragmas.nim.o c_code/1_2/saturate.nim.o c_code/1_2/guards.nim.o c_code/1_2/sighashes.nim.o c_code/1_2/sempass2.nim.o c_code/1_2/cgmeth.nim.o c_code/1_2/aliases.nim.o c_code/1_2/patterns.nim.o c_code/1_2/dfa.nim.o c_code/1_2/injectdestructors.nim.o c_code/1_2/liftlocals.nim.o c_code/1_2/lambdalifting.nim.o c_code/1_2/closureiters.nim.o c_code/1_2/transf.nim.o c_code/1_2/vmgen.nim.o c_code/2_2/vmdeps.nim.o c_code/1_2/vmmarshal.nim.o c_code/2_2/gorgeimpl.nim.o c_code/1_2/macrocacheimpl.nim.o c_code/1_2/evaltempl.nim.o c_code/2_2/vm.nim.o c_code/1_2/semmacrosanity.nim.o c_code/1_2/pluginsupport.nim.o c_code/1_2/plugins7locals.nim.o c_code/1_2/plugins7itersgen.nim.o c_code/1_2/plugins7active.nim.o c_code/1_2/semparallel.nim.o c_code/2_2/sem.nim.o c_code/1_2/ccgutils.nim.o c_code/1_2/ndi.nim.o c_code/1_2/cgendata.nim.o c_code/1_2/ccgmerge.nim.o c_code/1_2/enumtostr.nim.o c_code/2_2/stdlib_dynlib.nim.o c_code/1_2/cgen.nim.o c_code/1_2/passaux.nim.o c_code/1_2/depends.nim.o c_code/1_2/modules.nim.o c_code/1_2/jsgen.nim.o c_code/2_2/docgen2.nim.o c_code/1_2/main.nim.o c_code/2_2/scriptconfig.nim.o c_code/2_2/cmdlinehelper.nim.o c_code/2_2/nim.nim.o -ldl -lm -lrt
        ... : SUCCESS
   Building tools (nimble, nimgrep, nimpretty, nimsuggest)
  Executing ./bin/nim c koch
   Finished with exit code 1
     Output Hint: used config file '/home/demi/.choosenim/toolchains/nim-0.20.0/config/nim.cfg' [Conf]
        ... Hint: used config file '/home/demi/.config/nim/config.nims' [Conf]
        ... /home/demi/.config/nim/config.nims(1, 2) Error: unknown warning: ShadowIdent
        ...   
        ...    ^
 Exception: Execution failed with exit code 1
        ... Command: ./bin/nim c koch
        ... Output: Hint: used config file '/home/demi/.choosenim/toolchains/nim-0.20.0/config/nim.cfg' [Conf]
        ... Hint: used config file '/home/demi/.config/nim/config.nims' [Conf]
        ... /home/demi/.config/nim/config.nims(1, 2) Error: unknown warning: ShadowIdent
        ...   
        ...    ^
   Cleaning failed build
      Info: Not sending analytics because CHOOSENIM_NO_ANALYTICS is set.
      Info: Not sending analytics because CHOOSENIM_NO_ANALYTICS is set.
      Info: Not sending analytics because CHOOSENIM_NO_ANALYTICS is set.
      Info: Not sending analytics because CHOOSENIM_NO_ANALYTICS is set.
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Build failed
</code></pre>
</details>

**Comment by genotrance** [comment]
I checked koch.nim and it already sets `--skipUserCfg` since [Jan 2019](https://github.com/nim-lang/Nim/commit/42bac52426bf392fcfa3cfeeee716bec3166b709#diff-cbed6f667eb622190ddf224587036ea7R292). I'm not sure why it still pickks up the user config.nims. cc @timotheecour

That being said, choosenim now installs binary builds on Windows and Linux so this won't happen anymore, at least on these OS.

**Comment by dom96** [comment]
Please reopen if this is still a problem.
