### ISSUE TITLE
`Error: Spawning of process failed` caused by choosenim using a wrapper process

### ISSUE THREAD

**Issue by timotheecour** [dom96/choosenim#125]
choosenim is implemented by a binary that dispatches to the real nim binary; this causes some issues, for example see below.

I'm curious why isn't choosenim using symbolic links (at least on posix) which seems a simpler approach and avoids this kind of problem ?

```nim
# main.nim ($timn_D/tests/nim/all/t0496.nim)
import std/os
echo execShellCmd("pwd")
```

```
nim c -r main.nim
works
```

```
lldb -o run -- /pathto/Nim/nim c -r main.nim
works
```

```
choosenim /pathto/Nim/
which nim
/Users/timothee/.nimble//bin/nim

lldb -o run -- nim c -r main.nim
Error: Spawning of process failed. (Error was: Interrupted system call)
```

i'm on OSX
```
nim --version
Nim Compiler Version 0.20.99 [MacOSX: amd64]
Compiled at 2019-07-10
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: cb3c3c306c6507a09c15da26828a39fbbd4dbc66
active boot switches: -d:release
```
but this bug has always been there

**Comment by dom96** [comment]
I assume you accidentally created two issues that are mostly the same? #126

**Comment by timotheecour** [comment]
some github bug, it's happened before to me, sorry I have no control over that
