### ISSUE TITLE
"Nim binary is missing. Build failed." [Win10 x64, nim 0.20.2, old 0.19.4]

### ISSUE THREAD

**Issue by akavel** [dom96/choosenim#127]
## Problem

I unpacked choosenim and tried to run it to install nim 0.20:

```
C:\dnload\nim-etc\choosenim-0.4.0_windows_i386>runme.bat
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: y
Downloading Nim 0.20.2 from nim-lang.org
[#                                                 ] 0mb 0kb/s
      Info: Binary build unavailable, building from source
[##################################################] 100.0% 0kb/s
 Extracting nim-0.20.2.tar.gz
   Building Nim 0.20.2
 Exception: Nim binary is missing. Build failed.
   Cleaning failed build
       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: Build failed
        1 file(s) copied.
            Work finished.
            Now you must ensure that the Nimble bin dir is in your PATH:
              C:\Users\Mateusz\.nimble\bin
Press any key to continue . . .
```

## Additional info

NOTE: I have a previous installation of Nim 0.19.4 + MinGW active, done without choosenim; it reports as below:

```
C:\dnload\nim-etc\choosenim-0.4.0_windows_i386>nim --version
Nim Compiler Version 0.19.4 [Windows: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```

with `gcc.path = r"C:\dnload\nim-etc\nim\dist\mingw64\bin"` in my `C:\dnload\nim-etc\nim\config\nim.cfg`.

I also have some random ancient gcc in my PATH:

```
C:\dnload\nim-etc\choosenim-0.4.0_windows_i386>gcc --version
2.95
```

It would be super cool if the choosenim tool could report some more details about what's going on under the hood, or maybe log them to some file and print the path to this log file when it starts. As it is now, I find it hard to understand how I could further debug the issue myself :(

**Comment by akavel** [comment]
## Further attempts

Next thing I tried was removing the old `nim` installation (by renaming the directory) and then also downloading 0.20.0 instead of 0.20.2 (0.20.0 seems to be linked on the official install page of Nim); still no success:

```
C:\dnload\nim-etc\choosenim-0.4.0_windows_i386>cd choosenim

C:\dnload\nim-etc\choosenim-0.4.0_windows_i386\choosenim>choosenim.exe 0.20.0
Downloading Nim 0.20.0 from nim-lang.org
[#                                                 ] 0mb 0kb/s
      Info: Binary build unavailable, building from source
[##################################################] 100.0% 0kb/s
 Extracting nim-0.20.0.tar.gz
   Building Nim 0.20.0
 Exception: Nim binary is missing. Build failed.
   Cleaning failed build
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Build failed
```

**Comment by dom96** [comment]
That's very peculiar, here is why this error shows up: https://github.com/dom96/choosenim/blob/121133ba06b0954e058d38743a18fe1ad1f817f2/src/choosenim/builder.nim#L50

Can you run choosenim with ``--debug`` and paste the output?

**Comment by dom96** [comment]
also, does installing 0.19.4 using choosenim work for you?

**Comment by akavel** [comment]
I installed 0.20.2 by hand in the meantime; with it active, and with `--debug`, the output looks like this:

```
C:\dnload\nim-etc\choosenim-0.4.0_windows_i386>choosenim\choosenim.exe 0.20.0 --debug
     Debug: Reporting to analytics...
Downloading Nim 0.20.0 from nim-lang.org
[#                                                 ] 0mb 0kb/s
      Info: Couldn't download file from http://nim-lang.org/download/nim-0.20.0_x8.zip.
        ... Response was: 404 Not Found
     Debug: Reporting to analytics...
      Info: Binary build unavailable, building from source
      Info: C:\Users\Mateusz\.choosenim\downloads\nim-0.20.0.tar.gz already downloaded
 Extracting nim-0.20.0.tar.gz
     Debug: Reporting to analytics...
   Building Nim 0.20.0
 Exception: Nim binary is missing. Build failed.
   Cleaning failed build
   Warning: Cleaning failed: Proces nie mo┼╝e uzyska─ç dost─Öpu do pliku, poniewa┼╝ jest on u┼╝ywany przez inny proces.
     Debug: Reporting to analytics...
     Debug: Reporting to analytics...
     Debug: Reporting to analytics...
     Debug: Reporting to analytics...
     Error: Build failed
```

I got interested in why there's an attempt to download a `nim-0.20.0-x8.zip` (note the weird `-x8` suffix), and I believe this may be because of the ancient/broken (?) MinGW I have in PATH - specifically, I tried running the following command, [based on choosenim sources](https://github.com/dom96/choosenim/commit/7227aba1b858550f10f10025793142186b5e2e3b#diff-232a693dcba9b4e873154b917eaf7634R116):

```
C:\prog\dali>cmd /c echo int main^(^) { return sizeof^(void *^); } | gcc -xc - -o archtest && archtest
gcc: installation problem, cannot exec `cc1': No such file or directory
```

**Comment by genotrance** [comment]
Read through this one - choosenim and finish both simply use gcc if it is already present. There's no check for version levels. Both these tools only download mingw if no gcc is found.

Do you have any suggestions on how this should be improved?

**Comment by dom96** [comment]
Closing this since it's old and it's no clear what the solution here should be.
