### ISSUE TITLE
Feature Request: choosenim should install openssl on Windows

### ISSUE THREAD

**Issue by rayman22201** [dom96/choosenim#131]
Nimble requires openSSL 1.1 on Windows. But Windows is not guaranteed to have that version of openSSL installed. (Or OpenSSL installed at all. Windows has a it's own crypto libs.)

The goal of choosenim is to make it easy to install and manage the Nim environment, and choosenim already installs Mingw for the user.

It makes sense to me that choosenim should also detect and install openSSL if it is not detected on the system.

**Comment by dom96** [comment]
The Windows zips and executable of choosenim available in the releases page already includes openssl DLLs because choosenim itself depends on them, these should be copied along with choosenim during initial install.

If this doesn't happen then please reopen.

**Comment by rayman22201** [comment]
Just a note: After digging in to the code more, I realized that you are correct @dom96. the windows dll.zip includes these. But, my environment didn't pick up the dlls.

I'm not 100% sure, but I have a hunch the dll fetching may be tied to Mingw fetching. It detected my system Mingw, so it didn't fetch Mingw, but didn't fetch the dlls either.

I have to verify this, but fetching the dlls and fetching Mingw should not be tied together.
I will open a new bug if I figure it out.

**Comment by dom96** [comment]
the way it works is that the runme.bat file copies the DLLs. It does this always IIRC, but do check it.
