### ISSUE TITLE
Add nim-gdb to PATH

### ISSUE THREAD

**Issue by awr1** [dom96/choosenim#140]
Choosenim doesn't add the [nim-gdb](https://github.com/nim-lang/Nim/blob/devel/bin/nim-gdb) plugin to the PATH, perhaps this should be changed?

**Comment by dom96** [comment]
sure, we can add that I think

**Comment by genotrance** [comment]
https://github.com/nim-lang/Nim/issues/13104

**Comment by genotrance** [comment]
So bin/nim-gdb is a shell script - how do we shim this?

**Comment by dom96** [comment]
`ls ~/.nimble/bin`?

**Comment by ynfle** [comment]
```
balls
bump
c2nim
choosenim
choosenim_0.6.0
closure_compiler
clurp
exercism_test_runner
forum
inim
jupyternim
karun
loaf
markdown
nake
nestd
nim
nimble
nimgrep
nimlsp
nimpretty
nimsuggest
tempfile_seeder
testament
toast
```
