### ISSUE TITLE
forced telemetry?

### ISSUE THREAD

**Issue by xmonader** [dom96/choosenim#142]
```
➜ curl https://nim-lang.org/choosenim/init.sh -sSf | sh

choosenim-init: Downloading choosenim-0.4.0_linux_amd64
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: Forced Yes

```

**Comment by Calinou** [comment]
In a non-TTY interface (such as CI services), you can opt-out of telemetry by setting the environment variable `CHOOSENIM_NO_ANALYTICS=1`.

**Comment by xmonader** [comment]
@Calinou that's on my local machine I've no idea why it `forced yes `

**Comment by dom96** [comment]
Should be fixed now. Can you retest @xmonader?

**Comment by xmonader** [comment]
@dom96 yup looks like it 
![image](https://user-images.githubusercontent.com/64129/66803724-d56a0d80-ef20-11e9-96d5-63f0b6b89119.png)
