### ISSUE TITLE
Analytics data

### ISSUE THREAD

**Issue by juancarlospaco** [dom96/choosenim#144]
https://github.com/dom96/choosenim/blob/master/analytics.md#who-has-access

> Summaries of the data may be released in the future to the public.

We passed version `1.0` I think is time to release the data, at least once with every Nim release,
can be useful for people writing libraries and projects to improve. Once per release is not much work.
Can be just a JSON or CSV, and visualizations can be made by users who want it.
It can help to *Hype up* the launch of new releases.

**Comment by dom96** [comment]
> Once per release is not much work.

hah, releases are hard enough. I don't think we'll be doing this in the near future.
