### ISSUE TITLE
Auto opts-in if the shell isn't buffered

### ISSUE THREAD

**Issue by Skrylar** [dom96/choosenim#145]
```
choosenim-init: Downloading choosenim-0.4.0_linux_amd64
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: Forced Yes
Downloading Nim 1.0.0 from nim-lang.org
```

"Forced yes" is probably a bad default given the current situations in the Eurozone.

**Comment by Calinou** [comment]
You can set `CHOOSENIM_NO_ANALYTICS=1` before running the script to opt out of analytics.

I think opting out by default would be a better choice in non-TTY environments, but some other people here disagree :stuck_out_tongue:

**Comment by dom96** [comment]
How did you run this? This shouldn't happen anymore.

**Comment by genotrance** [comment]
Any update?
