### ISSUE TITLE
Install fails on Ubuntu 18.04.3

### ISSUE THREAD

**Issue by winks** [dom96/choosenim#148]
Just tried to install nim via choosenim as suggested on https://nim-lang.org/install_unix.html

This is the result: https://gist.github.com/winks/7332db98eceb0678cffb95bf7d3ef0b8

I only snipped all the `... Hint: xxx [Processing ]` lines

What I installed and did **not** help after reading https://github.com/dom96/choosenim#dependencies :

```
gcc-7-base:amd64                7.4.0-1ubuntu1~18.04.1
zlib1g-dev:amd64                1:1.2.11.dfsg-0ubuntu2
libssl-dev:amd64                1.1.1-1ubuntu2.1~18.04.5
build-essential (metapackage)
```

Not a real problem, the prebuilt binaries work fine. But if it's just a doc issue of deps this should probably be fixed on `install_unix.html` as beginners (this guy) are likely to try this.

**Comment by genotrance** [comment]
Will you be able to try running the specific failing command again and providing the output?

`gcc -c  -w -pthread -O3 -fno-strict-aliasing  -I/home/florian/.choosenim/toolchains/nim-1.0.4/lib -I/home/florian/.choosenim/toolchains/nim-1.0.4/nimsuggest -o /home/florian/.cach
e/nim/nimsuggest_r/linenoise.c.o /home/florian/.choosenim/toolchains/nim-1.0.4/lib/wrappers/linenoise/linenoise.c`

Unclear which specific dependency is missing from this.

**Comment by winks** [comment]
No sorry, I just tried it, but I can't reproduce it now - I suppose I accidentally installed the missing package, but no idea what it was, I was installing quite a few dev tools on that machine since then - now everything works.

Maybe it might work by just starting from a minimum 18.04.3 container/vm and just installing the 3-4 I mentioned.

**Comment by genotrance** [comment]
I tried this again with a bionic docker image and everything works fine with `build-essential`. If you skip that and only have the other 3 packages you listed, even `gcc` isn't present so nothing works. If you just install the `gcc` package then everything still works.

I noticed you are using v0.4.0 of choosenim. With 0.5.0, choosenim will now install a binary build of Nim on Linux which will avoid having to build Nim from scratch. That being said, you could still run into some other build issues.

Not sure what else to try on this.

**Comment by winks** [comment]
I'd say close the ticket, sounds like an edge case - thanks for your help :)
