### ISSUE TITLE
Manual nim builds work fine but installing choosenim fails

### ISSUE THREAD

**Issue by kaushalmodi** [dom96/choosenim#15]
Hello,

I can build nim manually using [this script][1]. 

I still I wanted to see what `choosenim` looked like, but I am unable to install it. It fails with this error:

```
> curl https://nim-lang.org/choosenim/init.sh -sSf | sh
choosenim-init: Downloading choosenim-0.2.2_linux_amd64
/tmp/choosenim-0.2.2_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/choosenim-0.2.2_linux_amd64)
/tmp/choosenim-0.2.2_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /tmp/choosenim-0.2.2_linux_amd64)
```

I am using RHEL 6.6.

Is that dependency failure for building `choosenim` or `nim`?

[1]: https://gist.github.com/261ba46487cbea9c6ad10c62ca2ee3e8

**Comment by dom96** [comment]
choosenim issue. I guess RHEL 6.6 has an older glibc than the Linux I built choosenim on :\

Next time I guess I'll need to set up an old Linux VM for building it.

**Comment by dom96** [comment]
Yeah, RHEL 6.6 has a glibc whose version is ~2.12.

I will set up artefacts for the Travis build which may give better support (as Travis runs builds on Ubuntu Trusty/Precise currently).

**Comment by kaushalmodi** [comment]
@dom96 Can you provide a musl compiled binary for `choosenim`. See https://github.com/kaushalmodi/hello_musl for example.

**Comment by kaushalmodi** [comment]
Hello, I tried choosenim after about a year today and looks like this issue has already been fixed. I am able to install Nim on RHEL 6.8 just fine.

Thanks!
