### ISSUE TITLE
detect lack of build-essentials on Linux and provide better errors

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#152]
https://irclogs.nim-lang.org/21-12-2019.html#10:06:10

**Comment by genotrance** [comment]
Unfortunately the snippet in the irc log is gone and it is unclear what exactly fails without build-essential. I tried on Debian bullseye with gcc and without build-essential and everything works so far.

**Comment by dom96** [comment]
lack of build-essential in that case meant that some header files were missing IIRC

**Comment by genotrance** [comment]
Yes but I tried building Nim from csources, koch boot, koch tools and a random Nim file and all work without build-essential installed. This is sid though so I am not sure if things have changed in Debianland.

**Comment by dom96** [comment]
If you've got time you can try reproducing this on the OS the user had: Ubuntu 18.04 as far as I can see from the logs.

**Comment by genotrance** [comment]
I just tried this for another [issue](https://github.com/dom96/choosenim/issues/148#issuecomment-573353100) and without gcc, nothing will work. With my previous PR, choosenim will exit right away if gcc is missing.

**Comment by dom96** [comment]
Okay, let's close this. CC @has1 in case you're on GitHub.
