### ISSUE TITLE
feature: `choosenim csources v0.19.0` (for bootstrapping older nims during bisect)

### ISSUE THREAD

**Issue by timotheecour** [dom96/choosenim#154]
see design idea discussed here: https://github.com/nim-lang/Nim/issues/13066#issuecomment-572262660
the idea is to allow automatically building nim at **any** prior commit (eg use case: for `git bisect`) and using an appropriate csources-built nim version as bootstrapping point is guaranteed to work, unlike any of the releases built by choosenim. For example (that occurred while bisecting for https://github.com/nim-lang/Nim/issues/13066):

```
git checkout 9985706fb812156fa6f805989063293ca71599df
choosenim 0.19.0 # ditto with 0.19.2 0.19.4 0.20.0
nim c -o:bin/nim_temp1 -d:release --skipParentCfg --skipUserCfg compiler/nim.nim
pathutils.nim(13, 22) Error: cannot open file: pathnorm
```
whereas it works if we build from csources at tag v0.19.0

**Comment by dom96** [comment]
csources at v0.19.0 should be the same as nim v0.19.0. How can one work and the other not?

**Comment by timotheecour** [comment]
ok i figured part of the problem, and a workaround:

after choosenim 0.19.0:
```
nim c -o:bin/nim_temp1 -d:release --skipParentCfg --skipUserCfg compiler/nim.nim
# pathutils.nim(13, 22) Error: cannot open file: pathnorm
# ditto with directly running `/Users/timothee/.choosenim/toolchains/nim-0.19.0/bin/nim c -o:bin/nim_temp1 -d:release --skipParentCfg --skipUserCfg compiler/nim.nim`
```

# workaround:
cp /Users/timothee/.choosenim/toolchains/nim-0.19.0/bin/nim bin/nim.0.19.0
bin/nim.0.19.0 c -o:bin/nim_temp1 -d:release --skipParentCfg --skipUserCfg compiler/nim.nim
```

so the build breaks if nim binary is outside of nim repo we are building.
While this works, is there a better workaround?

**Comment by timotheecour** [comment]
ok I found a better way: using --lib:lib
I know that flag is documented (very succintly... `set the system library pat`), but maybe we can improve its documentation as that's what shd be used to build older nims from another outside of source nim binary:
```nim
nim c -o:bin/nim_temp1 -d:release --skipParentCfg --skipUserCfg --lib:lib compiler/nim.nim
```
