### ISSUE TITLE
Update to stable doesn't select new version

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#17]
```
~ » choosenim update stable
   Updating stable
      Info: Already up to date at version 0.17.0
~ » choosenim show         
   Channel: stable
   Version: 0.16.0
      Path: /Users/dom/.choosenim/toolchains/nim-0.16.0
~ » choosenim -v                                                                                                               1 ↵
choosenim v0.2.2 (2017-05-17 22:47:01) [macosx/amd64]
```

**Comment by k0pernicus** [comment]
For this issue, you mean that `update` must switch the current toolchain to the requested one, if the current toolchain is different than the requested toolchain?

So, in your example, the correct response from `choosenim show` should be `Version: 0.17.0`, instead of `Version: 0.16.0`?

**Comment by dom96** [comment]
yep.

**Comment by k0pernicus** [comment]
Ok, I am working on it.

**Comment by dom96** [comment]
I'm on a bit of a spree so sorry if you've fixed this in your own time.
