### ISSUE TITLE
Include compiler git hash

### ISSUE THREAD

**Issue by mratsim** [dom96/choosenim#172]
I'm pretty sure this issue was raised somewhere but I couldn't find it.

As some of my libraries heavily depends on devel branch features and fixes (for example `{.align.}`) the only way to I have to avoid having users or me doing an unfruitful bug search is:
- Please update your compiler
- Or works for me, can you please recompile Nim manually and check if it works and confirm the git hash?

Having choosenim installation display the git hash just like Nim does when compiled from source would be an invaluable boon.

Example: https://github.com/mratsim/weave/issues/105

**Comment by genotrance** [comment]
Dup of https://github.com/dom96/choosenim/issues/57

I'm currently working on #12 so this should get addressed.

**Comment by genotrance** [comment]
This is fixed in #173 for devel / #head.
