### ISSUE TITLE
init.sh doesn't work in headless environment

### ISSUE THREAD

**Issue by yglukhov** [dom96/choosenim#18]
Tried running a MacOS autobuild on travis:

```
choosenim-init: Downloading choosenim-0.2.2_macosx_amd64
sh: line 46: /dev/tty: Device not configured
```

**Comment by dom96** [comment]
Indeed, we need to support a ``-y`` flag to the bash script.

**Comment by dom96** [comment]
In fact, I already have a TODO for this inside the script: https://github.com/dom96/choosenim/blob/master/scripts/choosenim-unix-init.sh#L41 :)
