### ISSUE TITLE
Only `bin` folder inside the `.choosenim\toolchains\nim-1.0.6` folder

### ISSUE THREAD

**Issue by mindv0rtex** [dom96/choosenim#180]
I followed the instructions to install nim using the choosenim tool. Then I tried to build a basic Hello World application and received the error of not finding the `.choosenim\toolchains\nim-1.0.6\lib\system.nim` file. I went inside the corresponding toolchain folder and saw that there wasn't anything there besides the `bin` folder. I manually extracted the entire `lib` folder from the downloaded `nim-1.0.6.zip` file and it compiled fine.

I'm not sure whether I screwed something up or this is a genuine bug.

Forgot to add - I'm on WIndows 10

**Comment by genotrance** [comment]
Can you please try recreating the issue with latest debug version of choosenim from the releases page?

**Comment by mindv0rtex** [comment]
Sure thing! Here's what I get. It says that access is denied, but the archive is partially extracted, so I don't think it is a permission issue...

```
C:\yan\dev\choosenim-0.5.1_windows_amd64\choosenim
λ choosenim-0.5.1_windows_amd64_debug.exe stable
Downloading Nim 1.0.6 from nim-lang.org
      Info: C:\Users\yan\.choosenim\downloads\nim-1.0.6_x64.zip already downloaded
 Extracting nim-1.0.6_x64.zip
     Error: C:\Users\travis\build\dom96\choosenim\src\choosenim.nim(267) choosenim
        ... C:\Users\travis\build\dom96\choosenim\src\choosenim.nim(248) performAction
        ... C:\Users\travis\build\dom96\choosenim\src\choosenim.nim(66) choose
        ... C:\Users\travis\build\dom96\choosenim\src\choosenim.nim(53) chooseVersion
        ... C:\Users\travis\build\dom96\choosenim\src\choosenim.nim(19) installVersion
        ... C:\Users\travis\build\dom96\choosenim\src\choosenimpkg\utils.nim(49) extract
        ... Unable to extract. Error was 'Access is denied.
        ... '.
```

**Comment by dom96** [comment]
I'm going to hope/guess that this is caused by the same thing as https://github.com/dom96/choosenim/issues/199
