### ISSUE TITLE
use symlinks instead of shims where symlinks are supported

### ISSUE THREAD

**Issue by timotheecour** [dom96/choosenim#189]
on OS that always support symlinks (most OS's including windows 10), choosenim should use symlinks instead of shims.
Shims cause performance overhead (if your nim command invocation is a simple one, eg `nim dump` or `nim --version` etc), and more importantly can cause issues, eg https://github.com/dom96/choosenim/issues/126 in the past but there are others.

another example is it's not easy from just `which nim` to tell which path is the underlying nim. I intend to add `path/to/nim` in `nim dump` but that's just a workaround.

The only question is what to do about windows, whether to auto-detect whether to use shims vs symlinks (depending on windows version), or (simpler IMO), let user choose via `choosenim --usesymlink:on/off [args...]`

## notes
* recently discussed on IRC https://gitter.im/nim-lang/Nim?at=5e89179230ec2e5a259b2b25 https://irclogs.nim-lang.org/04-04-2020.html#23:25:07
* windows10 supports non admin symlinks since 2016 https://www.wintellect.com/non-admin-users-can-now-create-symlinks-windows-10/

**Comment by dom96** [comment]
Shims aren't ideal, but they work consistently across OS'. I want to reduce complexity and because of that I am closing this unless there is a very real reason why these shims don't work.
