### ISSUE TITLE
choosenim doesn't detect the architecture of DLLs

### ISSUE THREAD

**Issue by euantorano** [dom96/choosenim#19]
The Windows self-extracting EXE in the current releases page does not include any of the DLLs required for Nim (such as `libeay32.dll`, `libcurl.dll`, etc.).

**Comment by TiberiumN** [comment]
AFAIK they're being downloaded when choosenim installs some nim version

**Comment by euantorano** [comment]
@TiberiumN They weren't on my install (0.16.0 which was installed by default and for `stable`, then 0.17.0, then HEAD) that's why I reported this. I talked to Dominik on IRC before reporting :)

**Comment by TiberiumN** [comment]
@euantorano IDK then, I downloaded choosenim and installed Nim from scratch without any issues (and all dll's are present).
My OS is Windows 10 Creators Update

**Comment by euantorano** [comment]
Interesting. I installed for the first time on Friday on Windows 10 Enterprise x64 (Creators Update).

**Comment by dom96** [comment]
Huh, that is strange. Thanks to @TiberiumN for reminding me that choosenim does this.

@euantorano do you perhaps have the DLLs already somewhere in your PATH? Here is the procedure that determines whether DLLs should be installed https://github.com/dom96/choosenim/blob/master/src/choosenim/switcher.nim#L54

**Comment by euantorano** [comment]
Nope, none of the DLLs were in my path (I know this because choosenim then failed to work after install because DLLs were missing). I did then manually download them from the Nim website.

**Comment by dom96** [comment]
@euantorano any chance you could investigate whether the proc I linked returns false for you?

**Comment by euantorano** [comment]
Sorry for the late response, I didn't get a tag when you mentioned me. I'll need to modify my path to remove them then investigate.

**Comment by euantorano** [comment]
That function returns `false` on my system, but `~/.nimble/bin` doesn't contain the DLLs, nor are they in my path. When I then try to run `choosenim`, I get the following error: `could not load: libeay32.dll`

**Comment by dom96** [comment]
@euantorano thanks. Weird. Can you run the self extracting exe and give me its output? The relevant code that downloads the DLLs is here: https://github.com/dom96/choosenim/blob/master/src/choosenim.nim#L52. If you could figure out why it doesn't run that would be great.

**Comment by dom96** [comment]
It likely does pick them up but they cannot be loaded. Probably because they are 64 bit.

**Comment by euantorano** [comment]
Yep, that seems to be the case indeed. Both of the DLLs are 64 bit versions.

**Comment by Calinou** [comment]
I can reproduce the missing `libeay32.dll` when trying to run `nimble` or `choosenim` (however, `nim` seems to work) after installing it with the self-extracting installer on Windows 10 64-bit, then adding the Nimble directory to the `PATH`.

**Comment by genotrance** [comment]
This can be marked fixed as well. Choosenim now checks for all DLLs in the archive, not just two. It was done for #53 in PR #135.
