### ISSUE TITLE
--nimargs: eg `choosenim 1.2.0 --nimargs -d:danger -d:nimEmulateOverflowChecks`

### ISSUE THREAD

**Issue by timotheecour** [dom96/choosenim#190]
example use case: for users who need custom build options, eg: -d:nimEmulateOverflowChecks

ref: https://irclogs.nim-lang.org/05-04-2020.html#21:18:19
> If choosenim needs to compile Nim for you then you cannot pass that flag to it

## proposal
`chosenim option --nimargs [args...]`
which forwards as is arguments to nim compilation commands

**Comment by dom96** [comment]
See my comments on IRC

**Comment by timotheecour** [comment]
please explain:

* https://irclogs.nim-lang.org/05-04-2020.html#21:37:06
> yeah, actually you may be able to do that without involving choosenim at all
> AFAIK there is a global cfg file that Nim will read

we should set global state (that may be read by other running processes etc) to pass options to choosenim

* https://irclogs.nim-lang.org/05-04-2020.html#21:37:42
> that said, when compiling Nim you usually build C sources... which won't have the code that the -d flag enables

csources ships with its own nimbase.h (from v0.20) which doesn't need `-d:nimEmulateOverflowChecks`

so csources will build fine, building a working Nim/bin/nim

then the `--nimargs` options can be forwarded to the next boostrapping steps:
```
Nim/bin/nim c $(nim_args...) koch 
./koch boot $(nim_args...)
```
