### ISSUE TITLE
choosenim installs Nim/config/nim.cfg  but not Nim/config/config.nims

### ISSUE THREAD

**Issue by timotheecour** [dom96/choosenim#193]
choosenim installs Nim/config/nim.cfg  but not Nim/config/config.nims

Nim/config/config.nims currently only contains this
```nim
when defined(nimHasCppDefine):
  cppDefine "errno"
  cppDefine "unix"
```
but might contain more in the future. In any case, this is a bug

```
\ls /Users/timothee/.choosenim/toolchains//nim-1.2.0/config
nim.cfg         nimdoc.cfg      nimdoc.tex.cfg
```

**Comment by genotrance** [comment]
This is not a choosenim issue which simply downloads the .zip or .xz file from nim-lang.org and extracts it. The file is missing in the archive.
