### ISSUE TITLE
choosenim "#head" invalid handle exception with mintty/msys (Git Bash) 

### ISSUE THREAD

**Issue by shmup** [dom96/choosenim#20]
You have to quote #head otherwise it's treated as a comment, however even quoting:

```
$ choosenim "#head"
Downloading Nim devel from GitHub
Error: unhandled exception: The handle is invalid.
 [OSError]
```

It works fine in cmd.exe

**Comment by genotrance** [comment]
choosenim now works on Travis for Windows and it uses git-bash. This should be working now.
