### ISSUE TITLE
Use of # character in nim version path makes CMake compilation fail

### ISSUE THREAD

**Issue by pmetras** [dom96/choosenim#205]
Building `drnim` tool in current `nim-#devel` compiles the Z3 library from sources using cmake. But the presence of a `#` character in choosenim toolchains path makes the compilation fail.
```
$ pwd
/home/pmetras/.choosenim/toolchains/nim-#devel

$ ./koch temp
bin/nim c -d:debug --debugger:native -d:nimBetterRun  -d:leanCompiler /home/pmetras/.choosenim/toolchains/nim-#devel/compiler/nim
Hint: used config file '/home/pmetras/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]

...

-- Z3_DEPENDENT_EXTRA_CXX_LINK_FLAGS: 
-- CMAKE_INSTALL_LIBDIR: "lib"
-- CMAKE_INSTALL_BINDIR: "bin"
-- CMAKE_INSTALL_INCLUDEDIR: "include"
-- CMAKE_INSTALL_PKGCONFIGDIR: "lib/pkgconfig"
-- CMAKE_INSTALL_Z3_CMAKE_PACKAGE_DIR: "lib/cmake/z3"
-- Adding component util
-- Adding component polynomial
-- Adding rule to generate "algebraic_params.hpp"
CMake Error at cmake/z3_add_component.cmake:118 (add_custom_command):
  add_custom_command called with OUTPUT containing a "#".  This character is
  not allowed.
Call Stack (most recent call first):
  src/math/polynomial/CMakeLists.txt:1 (z3_add_component)

...
```

I would say that is more a [cmake bug](https://gitlab.kitware.com/cmake/cmake/-/issues/12877) than a choosenim one, but the easiest workaround at the present time would be for choosenim to use a different path name.

**Comment by dom96** [comment]
Argh, that's an annoying bug. Honestly I'd rather avoid adding workarounds for things like this.

**Comment by genotrance** [comment]
We should be just downloading the Z3 binaries instead of building from scratch. Binary builder already covers every arch you can think of.

https://github.com/JuliaBinaryWrappers/z3_jll.jl/releases

**Comment by pmetras** [comment]
I don't know why araq decided to compile Z3 from sources. Perhaps see with him if compilation from source is really mandatory.

I had to copy the files in another directory and compile from there.

**Comment by dom96** [comment]
Sorry, but we won't be working around this.
