### ISSUE TITLE
choosenim devel often failed in macos

### ISSUE THREAD

**Issue by xflywind** [dom96/choosenim#219]
https://github.com/planety/prologue/runs/1193400510

```
Error: Error: Command failed: choosenim devel
fatal.nim(39)            sysFatal
Error: unhandled exception: download.nim(342, 14) `responseCode == 200` Expected HTTP code 200 got 403 for https://api.github.com/repos/nim-lang/nightlies/releases [AssertionError]

/Users/runner/work/_actions/jiro4989/setup-nim-action/v1/lib/installer.js:93
                    throw err;
                    ^

Error: Command failed: choosenim devel
fatal.nim(39)            sysFatal
Error: unhandled exception: download.nim(342, 14) `responseCode == 200` Expected HTTP code 200 got 403
```

https://github.com/jiro4989/setup-nim-action/issues/26

**Comment by dom96** [comment]
The 403 is because GitHub is rate limiting you. You can set GITHUB_TOKEN to fix this ([implemented here](https://github.com/dom96/choosenim/blob/98bcfce076c5a2e3e68653b5ddfe40f4410914fc/src/choosenimpkg/download.nim#L59)).

**Comment by dom96** [comment]
Another workaround is to not `choosenim devel`. You should depend on a concrete commit hash or version, otherwise you'll get flaky builds.
