### ISSUE TITLE
Add command to list available versions

### ISSUE THREAD

**Issue by samdmarshall** [dom96/choosenim#22]
There should be a subcommand `list` that lists out the available released versions so we don't have to guess at what is and isn't available (like, why `0.16.0` works but `0.16.1` does not).

**Comment by k0pernicus** [comment]
Maybe a local `list` command would be useful too, right?
I can work on this issue and propose a solution, if it's okay for you @dom96

**Comment by dom96** [comment]
@k0pernicus feel free to work anything you like. I may request some changes in PRs though :)

**Comment by samdmarshall** [comment]
has any work been made on this? it is something i could work on and submit a PR for?

**Comment by dom96** [comment]
go for it

**Comment by samdmarshall** [comment]
i'll give it my best; i cannot guarantee i can completely follow-through with this.
