### ISSUE TITLE
`curl https://nim-lang.org/choosenim/init.sh -sSf | sh -y` doesn't work; what's a 1 liner no-prompt alternative?

### ISSUE THREAD

**Issue by timotheecour** [dom96/choosenim#229]
`curl https://nim-lang.org/choosenim/init.sh -sSf | sh -y` doesn't work

is there a 1-liner simple alternative to:

```
curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
sh init.sh -y
rm init.sh
```

?
or is this the best one can do:

`(curl https://nim-lang.org/choosenim/init.sh -sSf > /tmp/init.sh; sh /tmp/init.sh -y; rm /tmp/init.sh)`

(avoiding init.sh which is a very generic name that overrite unrelated things)

**Comment by dom96** [comment]
That is the best you can do, although I wonder why the standard 1 line doesn't work for you.
