### ISSUE TITLE
Installation of #v0.16.0 now fails due to new c sources (?)

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#23]
The reason that this is installed in the first place is because it forces the newest Nimble to be installed together with Nim 0.16.0. Choosenim instructs the user to install Nim via the ``#v0.16.0`` tag when they attempt to use the older Nimble 0.8.2.

**Proposed solution:** Implement a ``--newest-nimble`` (or similar) flag to force the newest Nimble to be installed with whatever Nim version is selected.

This won't solve the issue that ``#v0.16.0`` cannot be installed, but it should solve the problem demi- was experiencing: https://irclogs.nim-lang.org/29-06-2017.html#20:52:04.

**Comment by genotrance** [comment]
This can be closed since csources is now locked and should build all 1.x releases.
