### ISSUE TITLE
I already have a c compiler

### ISSUE THREAD

**Issue by AmjadHD** [dom96/choosenim#237]
today i downloaded choosenim 0.7.2 on Windows 10 and ran the `runme.bat` script, and it started to download mingw, I already have msvc installed, I don't want it to install mingw, maybe ask the user before downloading a c compiler ?

**Comment by dom96** [comment]
A C compiler is a dependency for Nim. Nim cannot function without it. What's the issue with downloading it?

FWIW choosenim only downloads MINGW if there is no `gcc` in your PATH. MSVC might work, but in general it's better to get a known set of dependencies before installing Nim. Choosenim is about getting a working installation, not about supporting every possible configuration.

If you want to take a look at how choosenim determines whether to install MINGW: https://github.com/dom96/choosenim/blob/master/src/choosenimpkg/switcher.nim#L58
