### ISSUE TITLE
Windows install fails to create a working c++ build environment

### ISSUE THREAD

**Issue by JorySchossau** [dom96/choosenim#24]
I'm using choosenim-0.2.2_windows_i386.exe. A working c build environment is created and nim compiles hello world just fine. g++ also exists in the path as a result, but the cpp nim backend target breaks. Attempting to only use g++ to build a cpp hello world also breaks, resulting in the following wchar_s not found error:

```
$ g++ -o test.exe test.cpp                                                                                                    In file included from C:/Users/user/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/c++/cwchar:44:0,
                 from C:/Users/user/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from C:/Users/user/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/c++/iosfwd:40,
                 from C:/Users/user/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/c++/ios:38,
                 from C:/Users/user/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/c++/ostream:38,
                 from C:/Users/user/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/c++/iostream:39,
                 from test.cpp:1:
C:/Users/user/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/wchar.h:1040:29: fatal error: sec_api/wchar_s.h: No such
file or directory
 #include <sec_api/wchar_s.h>
                             ^
compilation terminated.`

**Comment by dom96** [comment]
Hrm, never seen this error before.

Could it be that the MinGW from Nim's site is defective? It seems it could be missing a header file.

@Araq any ideas?

**Comment by JorySchossau** [comment]
A manual install of MinGW64, followed by building from source with build64.bat, gave me no problems.

**Comment by dom96** [comment]
Any chance you could try a manual MinGW32 install?

**Comment by JorySchossau** [comment]
MinGW32 (from www.mingw.org/) works perfectly for me.

**Comment by dom96** [comment]
Okay, but what about this one? http://nim-lang.org/download/mingw32.zip

**Comment by dom96** [comment]
That's the one that choosenim uses.

**Comment by JorySchossau** [comment]
No, I get the same error in that case, using http://nim-lang.org/download/mingw32.zip

**Comment by Araq** [comment]
I think it's just that choosenim's way of installing mingw is competely wrong. You cannot move its binaries around, you need to keep it as it is and add it to the PATH. Which is exactly what ``finish.exe`` does. Sorry if I misremember of how choosenim does it.

**Comment by JorySchossau** [comment]
Choosenim is correctly installing mingw, but the mingw package it is using is broken, because the header file needed truly doesn't exist in the installation. Both 32 and 64 bit versions of mingw from mingw.org have the required header file (sec_api/wchar_s.h) and work just fine. Maybe just a git pull and repackage or equivalent is necessary?...

**Comment by dom96** [comment]
Indeed, I don't think this has anything to do with choosenim...

**Comment by JorySchossau** [comment]
So knowing what I know now, where should I file this issue? Or, who makes that mingw32 package hosted on nim-lang.org?

**Comment by dom96** [comment]
Sorry, I never replied to you. I submitted the bug report for you in the Nim repo https://github.com/nim-lang/Nim/issues/6219 :)

Closing here.
