### ISSUE TITLE
 Error: Unsatisfied dependency: nim (>= 1.0.8)

### ISSUE THREAD

**Issue by navvator** [dom96/choosenim#241]
Hello. I am on linux x64.

lukas@nwn_nl:~/.nimble/bin$ ./choosenim 1.0.8
Downloading Nim 1.0.8 from nim-lang.org
[##################################################] 100.0% 0kb/s
 Extracting nim-1.0.8-linux_x64.tar.xz
   Building Nim 1.0.8
  Compiler: Already built
     Tools: Already built
   Switched to Nim 1.0.8

lukas@nwn_nl:~/.nimble/bin$ nimble build -d:release
  Verifying dependencies for nwsync@0.2.6
 Installing neverwinter@>= 1.3.0
Downloading https://github.com/niv/neverwinter.nim using git
  Verifying dependencies for neverwinter@1.3.1
       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: Unsatisfied dependency: nim (>= 1.0.8)
i am also try nim devel and nim 1.2.6. and got same error... Whats i do wrong?

**Comment by dom96** [comment]
What does ``nim -v`` return?
