### ISSUE TITLE
nim-gdb on windows

### ISSUE THREAD

**Issue by reyqn** [dom96/choosenim#247]
When installing nim with choosenim on windows and then trying to run nim-gdb, I get this error:

`Error: Requested executable is missing. (Path: C:\Users\reyan\.choosenim\toolchains\nim-1.4.2\bin\nim-gdb.exe)
      Info: If unexpected, please report this error to https://github.com/dom96/choosenim`

So the nim-gdb shim from .choosenim tries to call the real one from .choosenim, however it doesn't seem to exist in nim releases for windows.

On the nim repo there is a nim-gdb.bat, but when using it, it will search for nim-gdb.py in .nimble (while the .py is in .choosenim).

I'm not really sure where to go from here.

Edit: for now, I just made a junction like this:
`mklink /J C:\Users\reyan\.nimble\tools C:\Users\reyan\.choosenim\toolchains\nim-1.4.2\tools`

It seems to work so far as a workaround.

**Comment by saem** [comment]
I don't think it's just Windows, but I'm encountering basically the same problem in Linux. `nim-gdb`can't work, it's proxying a shell/batch script which expects that `.nimble/tools/nim-gdb.py` exists.

Choosenim needs to be updated to either symlink (something?) in `/tools` from the nimble install and/or fix smaller tools like `nim-gdb` to work with choosenim and other scenarios.

**Comment by dom96** [comment]
> it's proxying a shell/batch script which expects that .nimble/tools/nim-gdb.py exists.

Isn't this a problem with the shell/batch script in that case?

**Comment by jmgomez** [comment]
Hi guys, it seems like this is still an issue in 1.6.0. Are there any workarounds?

**Comment by hyu1996** [comment]
+1, centos 8.2, choosenim v0.8.2, Nim Compiler Version 1.6.4

**Comment by dom96** [comment]
Please reopen in the Nim repo. I tested this on Linux and it works, I believe the script included in the Nim tarball needs to be fixed for Windows.
