### ISSUE TITLE
[bug] Unable to answer the start question on Linux x86_64

### ISSUE THREAD

**Issue by drygdryg** [dom96/choosenim#248]
Video demonstration (official installation method):

https://user-images.githubusercontent.com/43933400/103420777-227be300-4baa-11eb-93f7-d97bac591951.mp4

Installed from AUR (Arch Linux):

https://user-images.githubusercontent.com/43933400/103420791-332c5900-4baa-11eb-94b5-55b162d2c0dd.mp4

**Comment by pjgoodall** [comment]
affects me too...

**Comment by dom96** [comment]
Can one of you try and see if an older version works, for example 0.5.0? https://github.com/dom96/choosenim/releases/tag/v0.5.0

**Comment by drygdryg** [comment]
> Может ли кто-нибудь из вас попробовать и посмотреть, работает ли более старая версия, например 0.5.0? https://github.com/dom96/choosenim/releases/tag/v0.5.0

Yes, it works correctly.

**Comment by dom96** [comment]
With the new 0.8.0 release this will hopefully no longer be a problem.

**Comment by dom96** [comment]
This is likely the same as https://github.com/dom96/choosenim/issues/257 so closing.
