### ISSUE TITLE
choosenim doesn't modify path in Window 10

### ISSUE THREAD

**Issue by jtiai** [dom96/choosenim#254]
```
C:\> choosenim show
  Selected: #devel
   Channel: devel
      Path: C:\Users\jani\.choosenim\toolchains\nim-#devel

  Versions:
          * #devel
            1.4.6
            
C:\> nim --version
Nim Compiler Version 1.4.4 [Windows: amd64]
Compiled at 2021-04-18
Copyright (c) 2006-2020 by Andreas Rumpf
```

Expected nim version to be 1.5.1 compiled on 2021-04-24.

**Comment by dom96** [comment]
Yeah, I don't think it ever did. You should get a message to modify your PATH when installing choosenim for the first time.

**Comment by jtiai** [comment]
```
⨯ jani@CODE  ~\..\choosenim-0.7.4_windows_amd64  .\runme.bat
   Switched to Nim 1.4.6
        1 file(s) copied.
            Work finished.
            Now you must ensure that the Nimble bin dir is in your PATH:
              C:\Users\jani\.nimble\bin
```
That's the instruction I got and nimble bin is in my path. There are no additional instructions.

**Comment by jtiai** [comment]
Culprit was my path having actual nim installation before nimble directory.

**Comment by dom96** [comment]
I think it would be nice for choosenim to show a warning when `choosenim show` is used if another binary is in the PATH. https://github.com/dom96/choosenim/issues/37
