### ISSUE TITLE
Nimble not working

### ISSUE THREAD

**Issue by RyanDamerell** [dom96/choosenim#258]
When I type "nimble" into cmd I get the following error:
```
Error: Requested executable is missing. (Path: C:\Users\[user]\.choosenim\toolchains\nim-1.4.6\bin\nimble.exe)
      Info: If unexpected, please report this error to https://github.com/dom96/choosenim
```
From now on I'm going to use \~/ as a shortcut for my user folder, since it's easier.
I'm currently on windows, so if I run where.exe on 'nimble', I come up with '\~/.nimble/bin' instead of the path listed above. If I instead go to '\~/.choosenim/toolchains/nim-1.4.6/bin/' it doesn't have any nimble executable, even though it was supposed to install with nimble

**Comment by dom96** [comment]
That's odd, but suggests that the nightlies that choosenim downloaded didn't contain nimble. Can you run `choosenim 1.4.8 --debug` and paste the output? It might also just work

**Comment by kaushalmodi** [comment]
@RyanDamerell 

> Error: Requested executable is missing.

It's possible that your antivirus software thought that contains virus and took it out? See https://github.com/nim-lang/Nim/issues/17820 .

**Comment by dom96** [comment]
Yeah, my guess is it was your AV that did this.
