### ISSUE TITLE
"choosenim show path" command

### ISSUE THREAD

**Issue by aleclarson** [dom96/choosenim#260]
Some projects (like [napibindings](https://github.com/AjBreidenbach/napibindings)) need a command that prints only the path of the current Nim version.

```
$ choosenim show path
/Users/foo/.choosenim/toolchains/nim-1.4.8
```

**Comment by dom96** [comment]
Sounds like a nice first PR :)

**Comment by ilmanzo** [comment]
Hello, if it's free I'd like to give a try on this !

**Comment by dom96** [comment]
go for it! :)

**Comment by aleclarson** [comment]
thanks @ilmanzo  :)
