### ISSUE TITLE
choosenim stable fails with virus warning

### ISSUE THREAD

**Issue by bitstormFA** [dom96/choosenim#263]
After downloading 0.7.5 preview from github I tried to install stable but the process was stopped with a virus warning:

> .\choosenim-0.7.5-20201029-edc69bd_windows_amd64.exe stable
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: n
Downloading C compiler (Mingw64)
[##################################################] 100.0% 0kb/s
 Extracting mingw64.7z
Downloading DLLs (openssl, pcre, ...)
[##################################################] 100.0% 0kb/s
 Extracting dlls.zip
Downloading Nim 1.4.8 from nim-lang.org
[##################################################] 100.0% 0kb/s
 Extracting nim-1.4.8_x64.zip
   Building Nim 1.4.8
  Compiler: Already built
     Tools: Already built
oserr.nim(94)            raiseOSError
Error: unhandled exception: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
Additional info: "C:\\Users\\xxxx\\.choosenim\\toolchains\\nim-1.4.8\\bin\\nimble.exe -v" [OSError]

**Comment by dom96** [comment]
thanks for reporting, unfortunately there isn't much we can do about this. The antivirus companies just decided to mark many Nim programs as a virus for some silly reason.

**Comment by dom96** [comment]
https://github.com/nim-lang/Nim/issues/17820
