### ISSUE TITLE
Improve gcc detection logic

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#27]
Verify that the `gcc` in the user's PATH matches the arch of Nim (as is done in finish.exe).

**Comment by genotrance** [comment]
Why is this required? Assuming choosenim is downloading and building from scratch, it will simply build using the `gcc` in the path and the resulting binary will be the same arch.

**Comment by dom96** [comment]
A 64bit gcc will fail to build a 32bit Nim compiler.

**Comment by genotrance** [comment]
Still unclear on this - if `gcc` is pre-existing, the expectation is that the resulting Nim binary will be the same as the arch supported by `gcc`. Choosenim can highlight the arch it is building.

If choosenim is installing the `gcc` on behalf of the user and the platform is 64-bit, ask the user if he wants 32-bit or 64-bit?

**Comment by dom96** [comment]
64-bit support on Windows is non-existent via choosenim. If it was then sure, this could be done. It would still be nicer to detect it instead of asking the user who may potentially get it wrong (they may not even realise that they have a 'gcc.exe' installed)

**Comment by genotrance** [comment]
Main reason is that choosenim runs `build.bat` when building `csources` instead of detecting arch and running `build64.bat` so if you have a 64-bit compiler, it will be wrong.

**Comment by genotrance** [comment]
This can be closed.

**Comment by dom96** [comment]
Nice. You've fixed a lot :D

Next time please include "Fixes #xx" in your commits.
