### ISSUE TITLE
Latest 0.8.0 version broken, missing SSL support

### ISSUE THREAD

**Issue by kraptor** [dom96/choosenim#271]
```
[kraptor@pc ~]$ choosenim versions
httpclient.nim(865)      newConnection
Error: unhandled exception: SSL support is not available. Cannot connect over SSL. Compile with -d:ssl to enable. [HttpRequestError]
[kraptor@pc ~]$ choosenim update self
   Updating choosenim
httpclient.nim(865)      newConnection
Error: unhandled exception: SSL support is not available. Cannot connect over SSL. Compile with -d:ssl to enable. [HttpRequestError]
[kraptor@pc ~]$ choosenim --version
choosenim v0.8.0 (2021-10-03 16:16:27) [linux/amd64]
```

Seems the dependency has not been properly removed, as it's stated here in the Nim forum: https://forum.nim-lang.org/t/8476

Not sure what to do now, maybe downgrading?

**Comment by kraptor** [comment]
I updated with:

> choosenim update self

Afterwards, seeing that it broke because the SSL issue, I updated the binary manually (from the latest release on github) and it works. Not sure what happened. Is self-update broken?

**Comment by dom96** [comment]
You just got an old binary when you updated. I updated it afterwards and you then downloaded the fixed one.
