### ISSUE TITLE
Error in popular Github action to install nim (iffy/install-nim) possibly related to recent changes in choosenim 

### ISSUE THREAD

**Issue by pietroppeter** [dom96/choosenim#274]
here is the reference: https://github.com/iffy/install-nim/issues/14

**Comment by pietroppeter** [comment]
also causes failure in `nim/packages`: https://github.com/nim-lang/packages/runs/3787754295?check_suite_focus=true

**Comment by pietroppeter** [comment]
from @dom96 in discord (#internals):
> guess this is the cause: https://github.com/dom96/choosenim/blame/master/scripts/choosenim-unix-init.sh#L90
it's been in there for 14 months but I guess I never uploaded it to nim-lang.org until yesterday

the script is called in iffy/install-nim here:
https://github.com/iffy/install-nim/blob/575aa4e0a2a234107c404de8c566d69309abc084/install-nim.sh#L244

**Comment by iffy** [comment]
The most recent iffy/install-nim works. If you switch to `- uses: iffy/install-nim@v3.2.2` in your action files you should be fine.

**Comment by dom96** [comment]
And uploaded to server as well, let me know if that fixes it :)
