### ISSUE TITLE
Ask the user whether they want Nim added to PATH

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#28]
Also perform the modification of PATH automatically on all platforms.

**Comment by genotrance** [comment]
Doesn't choosenim copy the binaries to the ~/.nimble/bin directory for nim? Does that directory get added to the path automatically by nimble or does user have to manually do that?

I'm not sure what the requirement is so some clarity would help here.

**Comment by dom96** [comment]
> Doesn't choosenim copy the binaries to the ~/.nimble/bin directory for nim?

No, it creates a "proxy exe" in that directory.

> Does that directory get added to the path automatically by nimble or does user have to manually do that?

Manually.

This issue is about adding functionality to choosenim to add ``~/.nimble/bin`` to the PATH.

**Comment by genotrance** [comment]
Okay, makes sense. I presume we want this functionality in `nimble` as well - when a package with a `bin` is installed, it should ask and add to path accordingly.

Should it add to user or global path?

**Comment by genotrance** [comment]
I presume we want to add to path for Windows only, not for other OS?

**Comment by dom96** [comment]
All OS' would be nice. Windows is enough for now though.

**Comment by genotrance** [comment]
Is there a consistent way on Linux and Mac to do this? I can add to .profile but unsure if it's the right way.

**Comment by dom96** [comment]
Don't know. Please research how others do it if you're interested in implementing it.

**Comment by sschwarzer** [comment]
> Is there a consistent way on Linux and Mac to do this? I can add to .profile but unsure if it's the right way.

If the user is asked for the PATH edition on Posix systems, I think they should be told where choosenim will add the PATH change before agreeing.
