### ISSUE TITLE
GLIBC_2.27 Not found

### ISSUE THREAD

**Issue by sdmcallister** [dom96/choosenim#280]
I'm using centos7 and I see the following message after doing `choosenim update self`. 

`choosenim: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by choosenim)`

Trying to go back to a version that works. 

I see that somehow you can specify the version of choosenim using env variables, but I can't get this to work. 

I've tried:
```
export CHOOSENIM_CHOOSE_VERSION=v0.7.2/choosenim-0.7.2_linux_amd64
export CHOOSENIM_CHOOSE_VERSION=v0.7.2
```

**Comment by sdmcallister** [comment]
I noticed the old choosenim binary was still available so I just used it directly and was able to move to Nim 1.6..

**Comment by marcomq** [comment]
> Ubuntu 16.04 has been end of life'd April '21. 

I have this error on RHEL 7 / CentOs 7. I tried to install choosenim to compile a ManyLinux2014 binary for python. 
RHEL 7 seems still to be supported until 2024.

**Comment by sdmcallister** [comment]
We also just got RHEL 7 at work so this came up again which was disappointing.

**Comment by marcomq** [comment]
I know some people still using RHEL 6 on production. They are planning to upgrade - not sure if they want to use RHEL 7 or directly RHEL 8. But RHEL 7 is still something that is used out there and still considered to be stable.
It would be great to have at least CentOS 7 compatibility on build machines. 

I created some PR to automatically build binaries using a GH workflow 
https://github.com/dom96/choosenim/pull/296
It would use manylinux2014 to be CenOS 7 / RHEL 7 compatible.
I have no idea if the pre-compiled Nim binaries themself are CentOS 7 compatible...

**Comment by timotheecour4** [comment]
This issue also affects Amazon Linux EC2 instances (eg see https://stackoverflow.com/questions/72022527/glibc-2-27-not-found-while-installing-node-on-amazon-ec2-instance, https://repost.aws/questions/QUrXOioL46RcCnFGyELJWKLw/glibc-2-27-on-amazon-linux-2 => Glibc 2.26, not Glibc 2.27)

**Comment by dom96** [comment]
This should be resolved now. Thanks to @marcomq we now have builds on manylinux which hopefully will make choosenim work on these older distros :)
