### ISSUE TITLE
[FR] choosenim should have an option for building nim & nimble for current running target

### ISSUE THREAD

**Issue by dangbinghoo** [dom96/choosenim#285]
hi,  it would be great if choosenim support grabing current stable/devel version of nim & nimble source, and build it for current running target.

now, it's just grab the X86 arch binary whatever target it's running on.

thanks!

**Comment by dangbinghoo** [comment]
hmm, it seems that  `choosenim devel --latest` is building running target's nim from the latest devel source

**Comment by dom96** [comment]
yep ``choosenim devel --latest`` is what you want. Nimble versions are tied to Nim's so there isn't a way to choose Nimble (might be worth implementing too, but you can in effect choose nimble by installing a particular Nimble manually via `nimble install nimble@vX.X.X`
