### ISSUE TITLE
Choosenim depends on Nim 1.4.4

### ISSUE THREAD

**Issue by benob** [dom96/choosenim#287]
Choosenim depends on analytics which depends on puppy which depends on nim 1.4.4.
The travis job which uses nim 1.2.6 does not work because of this.

**Comment by dom96** [comment]
cool, thanks, we actually need to move to GitHub actions anyway.

**Comment by guzba** [comment]
We have merged and tagged puppy 1.5.3 which lowers puppy's Nim version requirement under that of choosenim.
