### ISSUE TITLE
proxy on windows

### ISSUE THREAD

**Issue by reyqn** [dom96/choosenim#288]
Since 0.8, choosenim uses puppy for downloads on windows, and because puppy doesn't support proxies, I can't make choosenim work behind a proxy on windows. Is there something I'm missing?

**Comment by guzba** [comment]
Recent Puppy releases make use of WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY and no longer use the COM API for HTTP. Perhaps proxies on Windows work now?
