### ISSUE TITLE
From Mr. Chris Banda, issue with unxz for choosenim-0.8.2_macosx_amd64

### ISSUE THREAD

**Issue by StefanSalewski** [dom96/choosenim#290]
Dear Sir,

unfortunately I am not the right person for problems related to
problems during the install process of the Nim compiler environment.

I stated in my book very clearly, that the book will not really try to
explain the install process -- for various reasons.

You are using the tool choosenim on macosx_amd64:

One obvious problem seems to be, that the program unxz is not
available. I can not tell you how you can install that tool on macosx,
but it is from this package: https://en.wikipedia.org/wiki/XZ_Utils

I will forward your message to the choosenim github issue tracker, see
https://github.com/dom96/choosenim in the hope that Mr. Picheta can
tell you more details. Generally, for problems with the Nim install
process you should try to use one of these issue trackers:

https://github.com/nim-lang/Nim/issues
https://github.com/dom96/choosenim
https://forum.nim-lang.org/

If you are not able to contact these destinations, I am willing to
forward your requests.

Best wishes,

Dr. Stefan Salewski.

On Thu, 2021-12-09 at 19:41 +0200, Chris Banda wrote:
> Hello Dr Stefan,
> 
> I trust this email finds you well. I'm trying to install Nim on my
> machine,
> this script is not working, I keep getting an error message.
> 
> ~ % curl https://nim-lang.org/choosenim/init.sh -sSf | sh
> 
> choosenim-init: Downloading choosenim-0.8.2_macosx_amd64
> 
> *    Prompt: *Can choosenim record and send anonymised telemetry data?
> [y/n]
> 
> *        ... *Anonymous aggregate user analytics allow us to prioritise
> 
> *        ... *fixes and features based on how, where and when people
> use
> Nim.
> 
> *        ... *For more details see: https://goo.gl/NzUEPf.
> 
> *    Answer: *y
> 
> *Downloading *Nim 1.6.0 from nim-lang.org
> 
> [##################################################] 100.0% 0kb/s
> 
> * Extracting *nim-1.6.0.tar.xz
> 
> *       Tip: *1 messages have been suppressed, use --verbose to show
> them.
> 
> *     Error: *Execution failed with exit code 127
> 
> *        ... *Command: unxz /Users/tm/.choosenim/downloads/nim-
> 1.6.0.tar.xz
> 
> *        ... *Output: /bin/sh: unxz: command not found

**Comment by dom96** [comment]
Need more info, what macOS version is this? Newer versions should have `unxz` bundled afaik

**Comment by tvooo** [comment]
Just tried to install nim on macOS Monterey, 12.1 (21C52), and ran into the same issue. I have the XCode CLI tools installed. Looks like latest macOS don't ship with it anymore.

I installed `xz` via Homebrew and after that the nim installation worked fine. Maybe worth adding a note to the install docs.
