### ISSUE TITLE
How to make choosenim look for ".choosenim/current" in another directory rather than $Home in Linux?

### ISSUE THREAD

**Issue by StarkBotsIndustries** [dom96/choosenim#295]
**Some Beginner Questions**

1. I want my nim commands (`nim c -r helloworld.nim`) to look for ".choosenim/current" in another directory than `$Home` in Linux. How can I do that? 

2. Is there a way to install binaries too in another directory than `$Home/.nimble/bin` so I don't have to `cp` to another directory and then add to path inititally?

Currently I'm using this command - `curl https://nim-lang.org/choosenim/init.sh -sSf | sh`

**Note** that I would prefer not to get a one time solution as I'm writing a buildpack, which is to be used in different machines where nim is not initially installed.

Thank You!

**Comment by dom96** [comment]
There are multiple ways:

* You can set the `HOME` env.
* You can also set `choonimDir` by passing `--choosenimDir`: https://github.com/dom96/choosenim/blob/master/src/choosenimpkg/cliparams.nim#L83. Where the binaries end up can also be overriden via the `nimbleDir` flag.
