### ISSUE TITLE
nimsuggest doesn't run on a fresh choosenim Windows install

### ISSUE THREAD

**Issue by movpasd** [dom96/choosenim#298]
Came across this issue as it breaks the VSCode Nim extension on Windows ([see issue](https://github.com/saem/vscode-nim/issues/97))

Steps to reproduce:

* Install choosenim using runme.bat on a Windows 10 machine
* Once it's installed, try running `nimsuggest` on the command line
* Observe the following error message

![image](https://user-images.githubusercontent.com/54367524/173307214-6651ef58-1b55-4618-9e2a-a1c7331126b3.png)

The DLL in question is not copied over from `.choosenim/toolchains/mingw64/bin` into `.nimble/bin` which might be the source of the issue. I think nimsuggest must assume there is a global MinGW installation in the PATH. This appears not to be an issue for the nim compiler `nim`, maybe because it doesn't directly access the DLLs but goes through choosenim's own MinGW proxies?

Current workaround: Adding `.choosenim/toolchains/mingw64/bin` manually to the global PATH works, but ofc this is not ideal since it kinda defeats the point of choosenim

Possible solution: Append `~/.choosenim/toolchains/mingw64/bin` to the process PATH before each execution

**Comment by dom96** [comment]
Does this work when Nim is installed via finish.exe?

**Comment by movpasd** [comment]
Doesn't seem to work either, so it might be a problem with nimsuggest -- but then I'm surprised the `nim` command works.

Then again it could be I didn't run my test properly, I did unset the relevant PATH variables for the test but perhaps I missed something (does Nim have any global config options or something that might have messed it up?)

**Comment by dom96** [comment]
`nim` doesn't need threads, nimsuggest could be different. Please report in Nim repo.
