### ISSUE TITLE
Redundant hint messages

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#30]
![screen shot 2017-08-25 at 14 23 54](https://user-images.githubusercontent.com/246651/29715884-15a47ab2-89a1-11e7-8a15-50989870d893.png)

Those hints are redundant when installing for the first time. Introduce a switch to disable them?

**Comment by k0pernicus** [comment]
Maybe I can try to solve this issue, in order to learn more Nim and to contribute to the Nim community.
What is the "switch" you want to introduce for this?

**Comment by dom96** [comment]
Yay. Awesome :)

Hrm, naming is tough.

Thinking of either ``--bootstrap`` or ``--first-install``. This won't be visible to the user so it doesn't matter too much, but it should be obvious to us. But yeah, pick whichever you like, I think I'm leaning towards ``--first-install``.

**Comment by k0pernicus** [comment]
`--first-install` is great.
I'll try to submit a PR at the end of the afternoon.

**Comment by dom96** [comment]
Fixed by #31.
