### ISSUE TITLE
possible issue with `update self` breaking choosenim (libcurl)

### ISSUE THREAD

**Issue by telatin** [dom96/choosenim#303]
Working on an old Linux (Ubuntu 16.04) server I realized I had nim 1.2.x installed, so I checked if `choosenim` was available.

It was (couldn't check the version) so I tried

```bash
choosenim update self
...
   Updating choosenim
[##################################################] 100.0% 0kb/s
      Info: Updated choosenim to version 0.8.4
```

but then invoking choosenim:
```text
$ choosenim
could not load: libcurl.so(|.4)
(compile with -d:nimDebugDlOpen for more information)
```

(`sudo apt-get install libcurl4-gnutls-dev` fixed the problem, but I was intrigued by the fact that choosenim was working before the update, so it might be worth a check ...)

**Comment by dom96** [comment]
Yeah, choosenim was updated to use libcurl because of an upstream bug: https://github.com/dom96/choosenim/commit/214b62971eb7053ef70e51de0e2908a0668404b7.  Surprised you need that package for libcurl.so to exist though. Maybe there is another .so that the curl wrapper doesn't know about?
