### ISSUE TITLE
Need to add `%UserProfile%\.choosenim\toolchains\mingw64\bin` to path for cpp

### ISSUE THREAD

**Issue by hcorion** [dom96/choosenim#309]
Just setup Nim on Windows 11 with choosenim, and whenever I compiled a nim file with C++ (via `nim cpp -r .\file.nim`) it would fail with a libgcc_s_seh-1.dll not found error.
I realized it was because the mingw64 toolchain path was not added to my user path, only the nimble path got added.
FWIW compiling the file with `nim c -r .\file.nim` works fine, I only had the dll issue with cpp.

**Comment by dom96** [comment]
This is caused by https://github.com/nim-lang/Nim/issues/19713.
