### ISSUE TITLE
Register winget package for Windows

### ISSUE THREAD

**Issue by adigitoleo** [dom96/choosenim#316]
Heading towards a v1.0 release, I wonder if a winget package could be registered for Windows. I try to manage all my significant windows packages through this new (official) CLI manager. I understand that some people may still prefer third party managers like chocolatey or similar, and even more people probably are happy with zip files, but [preparing the winget manifest](https://learn.microsoft.com/en-us/windows/package-manager/package/) does not seem too complicated and submitting the registry PR can be automated with github actions. I have not had any issues with winget so far (~1 year light use on two machines).

**Comment by adigitoleo** [comment]
Whoops I just remembered that they don't have a registrator bot (AFAIK) so I could just create the manifests and submit the PR manually. Not sure if there is even a way to automate it with actions after all, unless there is some kind of git-submodule magic that can be used here (I don't know enough about submodules).

**Comment by adigitoleo** [comment]
OK I found some more info. There are pending discussions about adding some kind of registration automation e.g. https://github.com/microsoft/winget-pkgs/issues/1515

There are some options like [following the PowerToys approach](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml) or using a new third-party [GH action](https://github.com/vedantmgoyal2009/winget-releaser).

**Comment by dom96** [comment]
If you're interested in getting it into winget then please do so.

**Comment by adigitoleo** [comment]
OK I'm happy to submit the manifest in that case. Draft of the files [here](https://github.com/adigitoleo/winget-pkgs/tree/choosenim/manifests/d/DominikPicheta/choosenim/0.8.4). One question: the nimble metadata suggests that this package is under the MIT license, but the LICENSE file is for BSD-3, which one is it?

**Comment by dom96** [comment]
BSD-3
