### ISSUE TITLE
Add a command to update choosenim by itself

### ISSUE THREAD

**Issue by k0pernicus** [dom96/choosenim#32]
If a new version of choosenim has been released, the only way to update it is to remove the current binary, and to run the bash script to install it.
What if adding a new command called `self`, to play with choosenim itself, like `self update` or something like that (like rustup)?

**Comment by dom96** [comment]
Do you really currently need to remove the current binary? I would have thought that simply running the shell script would be enough.

**Comment by k0pernicus** [comment]
Actually, I don't think we need to remove the current binary.
Maybe an easy way to run the shell script again, without searching the URL again :-)

**Comment by k0pernicus** [comment]
Interesting...
Are you interested by this feature? I can work on it

**Comment by dom96** [comment]
Too late, sorry :)
