### ISSUE TITLE
choosenim install stable command is locked at 1.6.8 version

### ISSUE THREAD

**Issue by dlesnoff** [dom96/choosenim#323]
`choosenim install stable` installs nim `1.6.8` when `1.6.12` is the latest stable version.
It might be related to the architecture problem in #315 .

**Comment by dom96** [comment]
https://github.com/dom96/choosenim/blob/d929b737ef6b042a946c88a5fd2cdee64af6c292/src/choosenimpkg/channel.nim#L13

```
curl -L http://nim-lang.org/channels/stable
1.6.12
```

Not a choosenim bug.

**Comment by dom96** [comment]
try `choosenim update stable`

**Comment by dlesnoff** [comment]
`choosenim update stable` works without problem. The problem was indeed the extra `install` word.
Sorry for the noise. Switching back and forth between nimble and choosenim can get confusing sometimes.
I am still surprised it did not throw an error this time.
