### ISSUE TITLE
Typo/spelling potentially

### ISSUE THREAD

**Issue by juancarlospaco** [dom96/choosenim#325]
The word "prioritise" is an alternative spelling used mostly only in Great Britain area, UK.

The American spelling of "prioritize" is the most widely accepted and used form in the world (North American and Oxford spelling). AFAIK.

Same with "anonymised" Vs "anonymized".

- https://github.com/search?q=repo%3Adom96%2Fchoosenim%20prioritise&type=code
- https://github.com/search?q=repo%3Adom96%2Fchoosenim+anonymised&type=code

**Comment by dom96** [comment]
As someone that lives in the UK I would argue that British English is the one true language and that the US is wrong. I certainly won't be changing how I write to match US English.
