### ISSUE TITLE
Choosenim abandoned?

### ISSUE THREAD

**Issue by marcusramberg** [dom96/choosenim#326]
This repo doesn't seem very actively maintained anymore. I think it should be moved into the `nim-lang` organization as it's the default suggested installer on the nim-lang home page? I guess it could also be forked, but transfering it seems more user friendly as github would automatically create a redirect from the old location. What are your thoughts, @dom96?

**Comment by PMunch** [comment]
We are working on restructuring the Nim tools in a better way, and part of this includes choosenim. That being said choosenim is a fairly simple tool, and it still works fine so there hasn't been a lot to do lately.

**Comment by dom96** [comment]
@marcusramberg Hey! Thanks for reaching out.

As you may or may not know I have stepped away from Nim. This project is open source so if anyone wishes to continue developing it they can do so. Judging by the message above it seems that is likely to happen.

All the best,
Dominik
