### ISSUE TITLE
Choosenim init script attempting pulling wrong version 

### ISSUE THREAD

**Issue by thatrandomperson5** [dom96/choosenim#345]
## Setup
OS: Ubuntu/Linux (Nix Shell)

## **Issue**:
As of now, a request to `https://nim-lang.org/choosenim/stable` gives version `0.8.5`, which does not exist. [[1]](https://github.com/dom96/choosenim/blob/master/scripts/choosenim-unix-init.sh#L34) This causes the init script to attempt to get version v0.8.5 from GitHub and stops with a 404 error, resulting in nothing being installed. [[2]](https://github.com/dom96/choosenim/blob/master/scripts/choosenim-unix-init.sh#L61)

TL;DR: Either the setup script need to be patched to avoid using the nim-lang.org link, the link needs to be fixed or 0.8.5 needs to be released.

**Note to future people**: This issue will most likely be fixed with time when 0.8.5 is released. Feel free to close this or remind me to close it when the time comes.

## **Workaround**:
Download the init script then replace the below before you run it.
```sh
local stable_version=
  if has_curl; then
    stable_version=`curl -sSfL https://nim-lang.org/choosenim/stable`
  elif has_wget; then
    stable_version=`wget -qO - https://nim-lang.org/choosenim/stable`
  fi
```
With 
```sh
local stable_version="0.8.4"
```

**Comment by SpotlightKid** [comment]
You need to get choosenim from https://github.com/nim-lang/choosenim now.

**Comment by thatrandomperson5** [comment]
> You need to get choosenim from https://github.com/nim-lang/choosenim now.

Ah, thank you. I was wondering why this hasn’t been updated in a few years and apparently it was migrated to another repository.

**Comment by thatrandomperson5** [comment]
New version works
