### ISSUE TITLE
Choosenim crash on Windows 10 (64-bit)

### ISSUE THREAD

**Issue by genotrance** [dom96/choosenim#35]
`> choosenim "#head"`

Downloading Nim devel from GitHub
Traceback (most recent call last)
choosenim.nim(155)       choosenim
choosenim.nim(136)       performAction
choosenim.nim(78)        choose
choosenim.nim(61)        chooseVersion
choosenim.nim(23)        installVersion
download.nim(227)        download
download.nim(212)        downloadImpl
download.nim(169)        downloadFile
download.nim(154)        downloadFileNim
httpclient.nim(1256)     downloadFile
httpclient.nim(951)      parseBody
httpclient.nim(892)      recvFull
httpclient.nim(866)      reportProgress
download.nim(150)        onProgressChanged
terminal.nim(657)        showBar
terminal.nim(396)        eraseLine
system.nim(2724)         sysFatal
Error: unhandled exception: over- or underflow [OverflowError]

**Comment by genotrance** [comment]
I could circumvent the issue in two ways. First was the easy way of putting the calls to eraseLine() in showBar() and showIndeterminateBar() in a try/except block. 

The second way was to use --overflowChecks:off during build.

I was unable to identify why the OverflowError is being raised in the first place though. From the code, there's no explicit OverflowError but I don't know what the compiler does behind the scenes.

**Comment by matkuki** [comment]
The crash is also present on Windows XP x86.

**Comment by euantorano** [comment]
Can confirm this on Windows 10 x64.

**Comment by dom96** [comment]
Will be fixed via https://github.com/nim-lang/Nim/commit/822da4b21352ca733c85b0f0303d0cf8f90e5aa6 in next release.

**Comment by dom96** [comment]
Should be fixed now.
