### ISSUE TITLE
Windows 7 Install Failure

### ISSUE THREAD

**Issue by monadler** [dom96/choosenim#36]
The gcc compiler was not downloaded before attempting to build nim. 

        ...      Error: Requested executable is missing. (Path: C:\Users\me\.choosenim\toolchains\mingw32\bin\gcc.exe)

Choosenim output attached.

[install-failure.txt](https://github.com/dom96/choosenim/files/1356716/install-failure.txt)

**Comment by genotrance** [comment]
This should no longer be an issue. Can you please verify?
