### ISSUE TITLE
Windows binaries detected as virus by Avira

### ISSUE THREAD

**Issue by jlmenut** [dom96/choosenim#40]
All is in the title, I sent them a report for false detection (I hope :) ) with a link to the file

**Comment by dom96** [comment]
yeah, sadly some anti virus software is too paranoid :)

**Comment by jlmenut** [comment]
The latest version of Avira doesn't flag the binary anymore

**Comment by dom96** [comment]
Oooh. They fixed it?

**Comment by jlmenut** [comment]
I suppose
