### ISSUE TITLE
Serve all downloads from GitHub?

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#42]
The SSL for nim-lang.org fails with ...

```
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

For some older versions of openssl. Serving from GitHub would solve that problem.

**Comment by dom96** [comment]
Might still be worthwhile, but we can do that later.

**Comment by genotrance** [comment]
Now that builds are automated, do we want to download from Github instead of nim-lang? It will save the turnaround of uploading to nim-lang.org and maintaining channels there.

**Comment by dom96** [comment]
Hrm, I dunno. That's when we should think about security, it might be that GitHub is in fact safer and that nim-lang.org may be hacked, or the other way around.

**Comment by genotrance** [comment]
Choosenim itself is hosted and downloaded from github. What's being asked here is whether Nim binaries should be downloaded from github but only source is currently hosted on github. Binaries are still only hosted on nim-lang.
