### ISSUE TITLE
Build of nim 0.17.2 fails when running the executable on Windows

### ISSUE THREAD

**Issue by dawkot** [dom96/choosenim#44]
> 
>   Info: Nim 0.17.2 already downloaded
>  Extracting nim-0.17.2.tar.gz
>    Building Nim 0.17.2
>  Exception: Execution failed with exit code 1
>         ... Command: build.bat
>         ... Output: gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code\1_1\compiler_nim.c -o c_code\1_1\compiler_nim.o
>         ... In file included from c_code\1_1\compiler_nim.c:7:0:
>         ... c_code/nimbase.h:482:13: error: size of array 'Nim_and_C_compiler_disagree_on_target_architecture' is negative
>         ...  typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
>         ...              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>         ... FAILURE
>         ... CSource compilation failed. Please check that the gcc compiler is in
>         ... the PATH environment variable, and that you are calling the batch script
>         ... that matches the target architecture of the compiler.
>    Cleaning failed build
>        Tip: 1 messages have been suppressed, use --verbose to show them.
>      Error: Build failed
>

**Comment by dom96** [comment]
Do you have a 64 bit GCC in your PATH?

**Comment by dawkot** [comment]
Yes

**Comment by dom96** [comment]
So that's your issue. Choosenim doesn't support 64bit yet. To use it, you can remove GCC from your PATH and try again (choosenim will download a 32bit GCC for you).

**Comment by dawkot** [comment]
It worked. Thanks.
