### ISSUE TITLE
Write location of stdlib to Nimble's config

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#49]
https://github.com/nim-lang/nimble#configuration

**Comment by genotrance** [comment]
What's the purpose of nimLibPrefix? Nimble doesn't seem to use it anywhere.

**Comment by dom96** [comment]
I think this was applicable when Nimble had a nimscript evaluator compiled in-- it needed to know the location of the Nim stdlib. No longer useful now that it calls Nim instead.
