### ISSUE TITLE
Please include further dlls in Windows installation

### ISSUE THREAD

**Issue by Feinbube** [dom96/choosenim#53]
Sorry to bother you again, but `nimble` does not work without installing the dlls from the "Other dependencies" package:
https://nim-lang.org/download/dlls.zip

Error message I got:
> could not load: libeay32.dll

I solved this, by downloading the dlls myself and putting them in the .nimble directory.
Would be great, if choosenim could do this for me ;)

**Comment by dom96** [comment]
It does do this for you: https://github.com/dom96/choosenim/blob/master/src/choosenim/download.nim#L273 (called here: https://github.com/dom96/choosenim/blob/master/src/choosenim.nim#L66).

I guess ``needsDLLInstall`` didn't return ``true`` on your system for some reason. If you could investigate why that would be a huge help :)

**Comment by Feinbube** [comment]
I looked into it:

* The choosenim release comes with the two DLL files. (They are part of the zip.)
* Thus, the function `needsDLLInstall` returns `false`.
* Thus, the additional libraries are not downloaded and installed.
* The two DLL files are also not copied to .nimble/bin

Since the DLL files are missing, neither `choosenim` nor `nimble` work properly afterwards. :/

**Comment by genotrance** [comment]
Easy fix is to check for some other DLL in the archive. I'll make a PR.
