### ISSUE TITLE
sh: 50: //tmp/choosenim-0.3.2_linux_amd64: not found

### ISSUE THREAD

**Issue by jakkn** [dom96/choosenim#60]
Looks like a bug in the install script adding double slashes.
```
root@1df60238e2ab:/tmp# curl https://nim-lang.org/choosenim/init.sh -sSf | sh
choosenim-init: Downloading choosenim-0.3.2_linux_amd64
sh: 50: //tmp/choosenim-0.3.2_linux_amd64: not found
root@1df60238e2ab:/tmp# ls /tmp
choosenim-0.3.2_linux_amd64
root@1df60238e2ab:/tmp#
```

**Comment by dom96** [comment]
hm, indeed. I wonder why it fails for you. Any ideas?

Here is the relevant line: https://github.com/dom96/choosenim/blob/master/scripts/choosenim-unix-init.sh#L50

**Comment by jakkn** [comment]
Ah, I thought it was the path to the executable but now I realize the docker image I'm trying to install in is a 32-bit environment. Is this not supported?

**Comment by dom96** [comment]
Choosenim doesn't support that I'm afraid.

**Comment by jakkn** [comment]
Good to know. Closing.
