### ISSUE TITLE
`choosenim update devel` results in "Error: unhandled exception: error: ... [SslError]"

### ISSUE THREAD

**Issue by gemath** [dom96/choosenim#61]
The full error:
`Error: unhandled exception: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [SslError]`

Is this just a problem with my network config and if it is, should this become an `unhandled exception`?

**Comment by dom96** [comment]
You likely have an outdated openssl installed on your system. Can you check the version?

**Comment by gemath** [comment]
It is openssl 1.1.0.h-1, Arch Linux is not on 1.1.1 yet.

**Comment by dom96** [comment]
Actually that might be too new :)

I'm guessing this is a Nim stdlib issue unfortunately :(

**Comment by gemath** [comment]
Oh damnit, I was using an old version of choosenim without realizing it. Installed the latest one over it and it all works, sry.
