### ISSUE TITLE
Can't Install any package

### ISSUE THREAD

**Issue by A-p-p-u** [dom96/choosenim#64]
Nimble attempts to read ~/.config/nimble/nimble.ini. Choosenim has not created such a directory.

**Comment by A-p-p-u** [comment]
I wish to add more details.

I am using Ubuntu 16.04 64 bit, with product: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz.


I have

    nim -v
    Nim Compiler Version 0.18.0 [Linux: amd64]

I was trying to install inim

    nimble install inim --verbose
    Reading official package list
    Downloading https://github.com/AndreiRegiani/INim using git
    Cloning latest tagged version: 0.2.5
    Setting Nim stdlib prefix to /home/appu/Nim
    Setting Nim stdlib path to /home/appu/Nim/lib
    Verifying dependencies for inim@0.2.5
    Error: Couldn't find Nim version.

I tried

    which nim
    /home/appu/.nimble/bin/nim

and

    whereis nim
    nim: /usr/lib/nim /etc/nim.cfg /usr/share/nim /home/appu/bin/nim /home/appu/.nimble/bin/nim /home/appu/Nim/bin/nim

What should I do?

**Comment by dom96** [comment]
Run ``nim -v`` and share the output.

**Comment by dom96** [comment]
It appears you have 3 different installations of Nim?

* /home/appu/Nim
* /home/appu/.choosenim/toolchains/
* /usr/lib/nim

I would try removing the old installations and try again.

**Comment by A-p-p-u** [comment]
Thanks a lot!!!
A suggestion: Choosenim should be able to smartly detect other installations (including those made without using choosenim, manually), and delete those installations, so as to always maintain system consistency.
