### ISSUE TITLE
choosenim-0.3.2_windows_i386.exe detected as malware by multiple anti-virus programs

### ISSUE THREAD

**Issue by AMP907** [dom96/choosenim#70]
Evidence: https://www.virustotal.com/#/file/9be90d6ea3f13910318e2f4d406d7881878ccd54adf20be65eeb2b4e9ee835f9/detection

**Comment by dom96** [comment]
That's obviously an antivirus bug, not a choosenim bug.

**Comment by AMP907** [comment]
Yes, you are correct, obviously this is not a fault with choosenim.

I was just trying to document which vendors are incorrectly detecting choosenim so they can be contacted and responses/progress tracked on choosenim's proper categorization. I have submitted a request with Microsoft to whitelist choosenim as Windows Defender does falsely detect it as of 7/15.

Sorry for the confusion.

**Comment by dom96** [comment]
No need to be sorry :)

Thank you for reporting it to Microsoft. I'll reopen this for the sake of future reference.

**Comment by genotrance** [comment]
No reason to leave this open.
