### ISSUE TITLE
choosenim install fails!

### ISSUE THREAD

**Issue by anypurpose** [dom96/choosenim#74]
use command  "curl https://nim-lang.org/choosenim/init.sh -sSf | sh" to install choosenim on a  DO VPS (CentOS 7.0 64X)
Failed with following messages:

![image](https://user-images.githubusercontent.com/7478640/43240179-c9d2691c-90c7-11e8-9197-39b609e1b67e.png)
![image](https://user-images.githubusercontent.com/7478640/43240200-e8d9ebaa-90c7-11e8-969f-3f6fd8e92dc5.png)

tried several times always the same result, very frustrating.
Please Help

Thank you

Feng

**Comment by dom96** [comment]
Your VPS doesn't have enough memory. Enable a swap partition or get more RAM.

**Comment by anypurpose** [comment]
thank you for the information
Best regards

Feng
