### ISSUE TITLE
Compilation error with preinstalled 64bit gcc

### ISSUE THREAD

**Issue by gekkonier** [dom96/choosenim#77]
Hi,
I tried to use choosenim on a Windows 10 Box to switch between stable and dev releases.
I use the 64bit gcc linked and provided from https://nim-lang.org/install_windows.html
I can use a regular nim installation and successfully compile simple nim source code.
I cleaned up my system completely from nim and ensured that the gcc is working.
Then I downloaded choosenim-0.3.2_windows_i386.zip from https://github.com/dom96/choosenim/releases.
After that I extracted that zip, opened a cmd and surfed into that directory.
There I started runme.bat
It didn't went well, there seems to be a compilation error (I edited out paths mentioning my user wit ********):

output starts here:

********\choosenim>runme
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: n
Downloading DLLs (openssl, pcre, ...)
[##################################################] 100.0% 0kb/s
 Extracting dlls.tar.gz
Downloading Nim 0.18.0 from nim-lang.org
[##################################################] 100.0% 0kb/s
 Extracting nim-0.18.0.tar.gz
   Building Nim 0.18.0
 Exception: choosenim.nim(206)       choosenim
        ... choosenim.nim(187)       performAction
        ... choosenim.nim(85)        choose
        ... choosenim.nim(72)        chooseVersion
        ... choosenim.nim(46)        installVersion
        ... builder.nim(91)          build
        ... builder.nim(23)          buildCompiler
        ... builder.nim(10)          buildFromCSources
        ... utils.nim(19)            doCmdRaw
        ... Execution failed with exit code 1
        ... Command: build.bat
        ... Output: gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code\1_1\compiler_nim.c -o c_code\1_1\compiler_nim.o
        ... In file included from c_code\1_1\compiler_nim.c:7:0:
        ... c_code/nimbase.h:477:13: error: size of array 'Nim_and_C_compiler_disagree_on_target_architecture' is negative
        ...  typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
        ...              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ... FAILURE
        ... CSource compilation failed. Please check that the gcc compiler is in
        ... the PATH environment variable, and that you are calling the batch script
        ... that matches the target architecture of the compiler.
       Tip: 7 messages have been suppressed, use --verbose to show them.
     Error: choosenim.nim(206)       choosenim
        ... choosenim.nim(187)       performAction
        ... choosenim.nim(85)        choose
        ... choosenim.nim(72)        chooseVersion
        ... choosenim.nim(46)        installVersion
        ... builder.nim(100)         build
        ... Build failed
        1 Datei(en) kopiert.
            Work finished.
            Now you must ensure that the Nimble bin dir is in your PATH:
              ********\.nimble\bin

**Comment by dom96** [comment]
choosenim install's its own gcc if it doesn't exist. But if one exists it just uses it, but choosenim only supports 32bit and since you've installed a 64 bit version you're getting problems...

**Comment by gekkonier** [comment]
Does that mean that if i try to use choosenim I will only succeed with 32 bit and i cannot use 64 bit toolchain?

**Comment by dom96** [comment]
yes: https://github.com/dom96/choosenim/issues/16
