### ISSUE TITLE
Support running toolchains side-by-side

### ISSUE THREAD

**Issue by arnetheduck** [dom96/choosenim#78]
`choosenim` currently supports only one toolchain at a time, using global state - this means it's hard to test two toolchains at a time - it also causes issues like cache sharing between different nim versions which leads to a sub-par experience (specially given Nim's poor handling of cache dirs in general, where it's common clearing the cache helps solve compile problems).

As an alternate approach, it would be nice if choosenim could work on a per-shell basis, for example by modifying `$PATH` to point to a specific environment, akin to how python handles `venv` - this environment would not only contain nim itself, but also the nimble dir, allowing it to be fully isolated from other development - this way, it becomes possible to work on two projects side-by-side and not worry about the dependencies of one project messing up the dependencies of the other.

ping @zah who has talked about something similar, leveraging the Nix package manager

**Comment by genotrance** [comment]
We could leverage the current proxyExe setup to behave differently for this scenario. Say, user runs `choosenim 1.0.4 -t` where `-t` means temporary. In this instance, choosenim will get the parent process ID which should be the shell pid and save an entry in `~/.choosenim/temporary` in a `pid = path` format. For cleanup purposes, choosenim will also delete all `pid = xxx` entries where the pid no longer exists.

Next, when a user runs any proxied binary, the proxy will check if any process pid in its process tree matches an entry in `~/.choosenim/temporary`. If it does, it will use that env. If none are found, it will use `~/.choosenim/current`.

Pro: leverage existing infrastructure
Con: might be slow searching pids for every proxy binary call

For setting unique Nimble or nimcache, choosenim could be run with a `--nimblePath:xxx` and `--nimcache:xxx` flags which will then always be forwarded by the proxy to the actual binary. They would need to be smart enough to know the different behaviors of the binaries being proxied. Seems a bit ugly though and ideally Nim and Nimble solve this some other way but doesn't seem likely.

**Comment by dom96** [comment]
You could always build upon choosenim and create a bash script that sets up the env for you so that for example `~/.choosenim/toolchains/nim-1.0.6/bin` is in your PATH.

Although I'm not entirely sure what this would solve.

**Comment by arnetheduck** [comment]
nim compiler versions are wildly incompatible between each release (for any codebase beyond the most trivial ones) - even patch releases - thus, it's often necessary to switch between versions, and certain code is tied to certain versions of the language - having a global nim with a global nimble repo simply isn't viable if one wants to use nim more seriously - thus, there needs to be tooling to allow these things to be controlled locally, preferably in such a way that when you enter a particular project, the right compiler environment is also selected for you - this is what `venv` does in python: creates an isolated, reproducible sandbox where things work as the author of some code intended.

**Comment by dom96** [comment]
Ahh, I see. You want choosenim to manage a separate Nimble directory for each Nim version. I think that this won't be useful as soon as we get lockfiles in Nimble, and even now that we've got localdeps in Nimble it should be much better. Because of this I don't think it's worth pursuing this, much better to focus on lockfiles.

**Comment by arnetheduck** [comment]
No, like the title says, I want to manage whole toolchains, including the compiler and its standard library, which after all is just one more dependency like anything else. Unless the compiler is made part of the lock file of course, which in general would make sense..
