### ISSUE TITLE
choosenim hangs when installing invalid versions on slow network

### ISSUE THREAD

**Issue by kayabaNerve** [dom96/choosenim#79]
choosenim hangs after `Downloading Nim 17.0 from nim-lang.org`, and when I send SIGINT, the following is shown: 

```
choosenim.nim(206)       choosenim
choosenim.nim(183)       performAction
choosenim.nim(153)       update
choosenim.nim(34)        installVersion
download.nim(250)        download
download.nim(244)        downloadImpl
download.nim(192)        downloadFile
download.nim(177)        downloadFileNim
httpclient.nim(1297)     downloadFile
httpclient.nim(1227)     get
httpclient.nim(1219)     request
httpclient.nim(1196)     request
httpclient.nim(1165)     requestAux
httpclient.nim(1107)     newConnection
net.nim(1568)            dial
SIGINT: Interrupted by Ctrl-C.
```

I have a Lubuntu 17.10 VM. The rest of my network seems fine, and I can connect to the Nim website properly. I did successfully download/compile/install devel with choosenim.

**Comment by dom96** [comment]
``17.0``? Did you run ``choosenim 17.0``?

**Comment by kayabaNerve** [comment]
Yep. I'm idiotic. Never mind then...

Feature request to timeout/have an invalid version message?

**Comment by dom96** [comment]
Yeah, it still shouldn't hang

**Comment by genotrance** [comment]
Just tried this locally and it failed immediately.

`Version 17.0 does not exist.`

**Comment by dom96** [comment]
This is related to https://github.com/dom96/choosenim/issues/182. We need a way to timeout network connections quicker.

**Comment by dom96** [comment]
We use curl now
