### ISSUE TITLE
Doesn't seem to work through proxy

### ISSUE THREAD

**Issue by trialism** [dom96/choosenim#81]
Stuck at `choosenim-init: Downloading choosenim-0.3.2_linux_amd64`. I have HTTP_PROXY and HTTPS_PROXY properly set.

**Comment by dom96** [comment]
The script is using ``curl``: https://github.com/dom96/choosenim/blob/master/scripts/choosenim-unix-init.sh#L39

So I'm not sure what could be wrong, maybe you can investigate?

**Comment by trialism** [comment]
I don't know, curl is working fine for everything. But this script and nimble doesn't work through proxy for me.

**Comment by trialism** [comment]
`/tmp/choosenim-0.3.2_linux_amd64 stable --firstInstall < /dev/tty` (`"/$temp_prefix/$filename" $CHOOSE_VERSION --firstInstall < /dev/tty`) stucks

**Comment by trialism** [comment]
Here: [download.nim:148](https://github.com/dom96/choosenim/blob/01443835118fecd1d1401e8d94fece99dfa01046/src/choosenim/download.nim#L148) - environment variables should be in capital.

**Comment by trialism** [comment]
Prepared https://github.com/dom96/choosenim/pull/82

**Comment by trialism** [comment]
And this: https://github.com/nim-lang/nimble/blob/c249f9b83693f1623c982bb505b319248c1635bf/src/nimblepkg/options.nim#L378 is why I can't download dependencies with nimble when using a proxy...
