### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#85]
Permission denied when another user used choosenim.

This is because the ``untar`` package places extracted files in ``/tmp/untar-nim/nim-0.18.0`` and if another user used it then it cannot be overwritten.

**Comment by IterableTrucks** [comment]
The bug still exists in v0.4.0

**Comment by genotrance** [comment]
choosenim now uses nimarchive which creates a unique tempdir for each extraction. This can be closed.

https://github.com/genotrance/nimarchive/blob/master/nimarchive.nim#L54
