### ISSUE TITLE
nimble complains about OpenSSL on OS X 10.11.6

### ISSUE THREAD

**Issue by panta** [dom96/choosenim#87]
I've OpenSSL 1.0.2p from Homebrew.

Installation with choosenim goes without troubles, but when later I try any nimble command I get an error about OpenSSL being too old:

```bash
$ nimble refresh
Downloading Official package list
       Tip: 5 messages have been suppressed, use --verbose to show them.
     Error: nimble.nim(1106)         nimble
        ... nimble.nim(1042)         doAction
        ... nimble.nim(44)           refresh
        ... packageinfo.nim(229)     fetchList
        ... Refresh failed
        ... Could not download: Please upgrade your OpenSSL library, it does not support the necessary protocols. OpenSSL error is: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

I've tried removing ~/.nimble ~/.cache/nim ~/.choosenim, installing curl from homebrew, and re-installing with choosenim after setting `PATH`, `LDFLAGS`, `CPPFLAGS`, `PKG_CONFIG_PATH` for homebrew-installed openssl (1.0.2p) and curl (7.61.1), but the result is the same.

It seems that the installed nimble uses system openssl and/or curl, instead of the homebrew ones.

Is there any workaround?

**Comment by dom96** [comment]
Second bullet: https://github.com/nim-lang/nimble#troubleshooting
