### ISSUE TITLE
Add nimpretty to the list of installed tools

### ISSUE THREAD

**Issue by moigagoo** [dom96/choosenim#92]
There is no easy way to install nimpretty. The only option you have is to clone the Nim repo and build nimpretty fro source.

Meanwhile, Nim's VSCode extension can format code with nimpretty, so it's be quite handy to have it installed.

**Comment by moigagoo** [comment]
`koch tools`. however, does build `nimpretty` ¯\_(ツ)_/¯

**Comment by dom96** [comment]
oh, then it is a choosenim bug :)

**Comment by moigagoo** [comment]
Should be fixed in https://github.com/dom96/choosenim/pull/95

**Comment by dom96** [comment]
Fixed via #95.
