### ISSUE TITLE
Package not found error... !

### ISSUE THREAD

**Issue by vinodvinu** [dom96/choosenim#93]
Hi, when i tried to install choosenim, this is what happened.
---------------------------Error message-------------------------------------------------
E:\Synced Folder\Dropbox\Nim Folder\choosenim-master>nimble install choosenim
    Prompt: choosenim not found in any local packages.json, check internet for u
pdated packages? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
       Tip: 5 messages have been suppressed, use --verbose to show them.
     Error: Package not found.

E:\Synced Folder\Dropbox\Nim Folder\choosenim-master>

**Comment by dom96** [comment]
Nowhere does it say that you should be installing it via Nimble.

Follow these instructions: https://github.com/dom96/choosenim#installation

**Comment by vinodvinu** [comment]
I cant find a "runme.bat in my extracted folder.

**Comment by vinodvinu** [comment]
This is the extracted files in my pc. See this pic
[https://drive.google.com/open?id=1EZSV-kh8KngrSGogSjaxZIpi2CBR0ec3](url)
