### ISSUE TITLE
"runme.bat  is not in my extracted folder.

### ISSUE THREAD

**Issue by vinodvinu** [dom96/choosenim#94]
This is the extracted files in my pc. Please see this pic
https://drive.google.com/open?id=1EZSV-kh8KngrSGogSjaxZIpi2CBR0ec3

**Comment by vinodvinu** [comment]
Its installed and it shows that a "Switched to Nim 0.19.0". Ok. But when i typed "nim" in cmd, it shows me that the current nim version is 0.18.0. Then what is actually switched ?.

**Comment by dom96** [comment]
You've got an old Nim in your PATH. Make sure you change the PATH to point to where choosenim instructed you.

**Comment by vinodvinu** [comment]
So choosenim don't do this automatically ?

**Comment by vinodvinu** [comment]
And choosenim not instructed me anything.  When i run the "runme.bat", it says that it switched to nim 0.19.0

**Comment by vinodvinu** [comment]
I have a folder in my pc like this -
C:\Users\Vinod\.choosenim\toolchains\nim-0.19.0
Do i need to add this in "PATH" ?

**Comment by dom96** [comment]
You need to add `C:\Users\Vinod\.nimble\bin` to your PATH.

**Comment by vinodvinu** [comment]
Somehow i managed to add nim 0.19's path to PATH. So now CMD is giving the latest version. Now, how do i check that my code is compiled with latest nim compiler ?
This is what i tried
```nim
var aSeq : seq[int]     # I read that nim 0.19 not needed a " = @[] " here.
aSeq .add(500)
echo aSeq 
```
But this code returned this error msg.
```nim
(Attempt to read from nil?)
```

**Comment by vinodvinu** [comment]
@dom96 ,
`C:\Users\Vinod\.nimble\bin` is already in PATH

**Comment by vinodvinu** [comment]
@dom96 ,
From your github page, it is not clear to me that how to use choosenim. 
 Do i need to use choosenim by CMD ? If so my CMD is not recognaizing choosenim. 
Why i am asking this question because  this is my assumption.
1. Open CMD
2. type choosenim
3. It will show all installed versions of nim
4. Choose your desired version number.
5. Press enter.  Done !
Is this the process ? Please correct me.

**Comment by vinodvinu** [comment]
Thanks @dom96 , I got an advise to remove all old installations and install nim 0.19 freshly.

**Comment by genotrance** [comment]
Can we close this?
