### ISSUE TITLE
Clean up after building a version to save space

### ISSUE THREAD

**Issue by PMunch** [dom96/choosenim#98]
Talked to someone with not a whole lot of space left on their device that wanted to give Nim a try today. Checked how much `choosenim` was using on my system and it showed a pretty steep 4.1G of used space. I've got about 9 versions installed, but 0.19.0 alone is almost half a gig large. The main culprit for each version appears to be the c_code folder. The downloads folder is another half gig combined. It would be nice if choosenim could clean up these files that are no longer used for anything so that it didn't hog as much space.

**Comment by kaushalmodi** [comment]
Woh! Why is that? A Nim installation takes just 37MB on my RHEL 6.8.

**Comment by konradmb** [comment]
@genotrance Any progress in c_code removing? I'm removing it manually after every install to save ~700 MB of space.

**Comment by genotrance** [comment]
Now that we have Linux binaries, I need to update choosenim to get those instead. Regardless, this is a useful improvement and I'll look into it.

**Comment by dom96** [comment]
A good approach to this would be to store a single C sources checkout.

**Comment by genotrance** [comment]
This won't work since each release has its own corresponding csources. Having a single checkout won't be useful.
