### ISSUE TITLE
"v0.19.2" should be an allowed version string

### ISSUE THREAD

**Issue by mjoud** [dom96/choosenim#99]
Nim releases are tagged with a leading "v" as in "v0.19.2" but choosenim requires version to be specified as "0.19.2".

**Comment by sschwarzer** [comment]
On the other hand, "v0.19.2" is a tag, not a version. :-) I never considered the "v" a part of the version.

**Comment by dom96** [comment]
Meh. This probably isn't important enough. If you feel strongly about it I'll accept a PR but I won't spend time on it :)
